# v3.35 → v3.35.1 (S1619): „Klientas atsiėmė“ — WC completed laiškas off (tema „išsiųstas!“), savas laiškas su PVM sąskaitos PDF (šablono laukai iv_tema/iv_tekstas). Tikslūs replace su sargais, php -l STABDIKLIS.
import sys,subprocess,hashlib
s=open('/home/claude/ps/petshop-darbalaukis-v335.php',encoding='utf-8').read()
assert hashlib.md5(s.encode()).hexdigest()=='51172cea296c748ca96ff4f18a150917','baseline ne v3.35'
def rep(a,b,cnt=1):
    global s
    if s.count(a)!=cnt: print('FAIL',s.count(a),a[:100]); sys.exit(1)
    s=s.replace(a,b)
rep("\tconst VERSIJA = '3.35';","\tconst VERSIJA = '3.35.1';")
rep(" * Petshop Darbalaukis v3.35 (S1617/S1618/S1619,"," * Petshop Darbalaukis v3.35.1 (S1617/S1618/S1619,")
rep("filtras „Pristatymas“ + „Atsiėmimas AV / kita“); po v3.20)",
    "filtras „Pristatymas“ + „Atsiėmimas AV / kita“; v3.35.1: „Klientas atsiėmė“ — WC „įvykdytas“ laiškas (temos tema „išsiųstas!“) išjungtas, siunčiamas savas laiškas su PVM sąskaitos PDF (šablono laukai `iv_tema` / `iv_tekstas`, Claude siūlymas — Raimis tvirtina)); po v3.20)")
rep("\t\t$o->add_order_note( sprintf( 'Darbalaukis: klientas atsiėmė prekes AV (%s) — užsakymas įvykdytas be siuntos. PVM sąskaita klientui — WC „užsakymas įvykdytas“ laiškas.', $u->display_name ), false, true ); $o->save();\n\t\t$o->update_status( 'completed', '' );\n\t\t$o = wc_get_order( $o->get_id() );\n\t\tif ( 'completed' !== $o->get_status() ) { return array( 'dl_klaida', 'užbaigti nepavyko (būsena ' . $o->get_status() . ') — pakartok arba pasakyk Raimiui' ); }\n",
    "\t\t$o->add_order_note( sprintf( 'Darbalaukis: klientas atsiėmė prekes AV (%s) — užsakymas įvykdytas be siuntos. WC „įvykdytas“ laiškas (tema „išsiųstas“) NESIŲSTAS — siunčiamas darbalaukio laiškas su PVM sąskaita.', $u->display_name ), false, true ); $o->save();\n\t\tself::d( 'laiskai_off' ); $o->update_status( 'completed', '' ); self::d( 'laiskai_on' ); // v3.35.1: WC completed laiško tema „Jūsų užsakymas Nr.N išsiųstas!“ atsiėmimui netinka\n\t\t$o = wc_get_order( $o->get_id() );\n\t\tif ( 'completed' !== $o->get_status() ) { return array( 'dl_klaida', 'užbaigti nepavyko (būsena ' . $o->get_status() . ') — pakartok arba pasakyk Raimiui' ); }\n\t\t$laiskas = self::ats_ivykdyta_laiskas( $o ); $o->add_order_note( 'Darbalaukis: atsiėmimo laiškas su PVM sąskaita — ' . $laiskas . '.', false, true ); $o->save();\n")
rep("\t\treturn array( 'dl_info', 'klientas atsiėmė — užsakymas įvykdytas' . ( $o->get_meta( '_petshop_avpn_number' ) ? ', PVM sąskaita ' . $o->get_meta( '_petshop_avpn_number' ) : '' ) );\n",
    "\t\treturn array( 'dl_info', 'klientas atsiėmė — užsakymas įvykdytas' . ( $o->get_meta( '_petshop_avpn_number' ) ? ', PVM sąskaita ' . $o->get_meta( '_petshop_avpn_number' ) : '' ) . ' · ' . $laiskas );\n")
rep("\t\t\t'adresas'    => 'Liucionių g. 46, Liucionys (Nemenčinės sen., Vilniaus r.)',\n\t\t\t'valandos'   => 'I–V 09:00–18:00, VI 10:00–15:00',\n\t\t);\n\t}\n",
    "\t\t\t'adresas'    => 'Liucionių g. 46, Liucionys (Nemenčinės sen., Vilniaus r.)',\n\t\t\t'valandos'   => 'I–V 09:00–18:00, VI 10:00–15:00',\n\t\t\t'iv_tema'    => 'Užsakymas Nr. {nr} atsiimtas — PVM sąskaita faktūra Nr. {avpn}',\n\t\t\t'iv_tekstas' => \"Sveiki, {vardas}.\\n\\nAčiū, kad atsiėmėte užsakymą Nr. {nr}. Pridedame PVM sąskaitą faktūrą Nr. {avpn} ({suma} €).\\n\\nGražios dienos,\\nPetshop.lt komanda\\n+370 681 87787\\nterra@petshop.lt\",\n\t\t);\n\t}\n\n\t/** v3.35.1: laiškas po „Klientas atsiėmė“ — su PVM sąskaitos PDF (`_petshop_completed_pdf`, temos sugeneruotas completed metu). Grąžina tekstą pastabai. */\n\tprotected static function ats_ivykdyta_laiskas( $o ) {\n\t\t$el = $o->get_billing_email(); if ( ! is_email( $el ) ) { return 'el. pašto nėra — sąskaitą atspausdink (skydelio „Sąskaitos“)'; }\n\t\t$s = self::ats_laisko_sablonas(); $vardas = trim( (string) $o->get_billing_first_name() ); $avpn = (string) $o->get_meta( '_petshop_avpn_number' );\n\t\t$z = array( '{vardas}' => $vardas ? $vardas : 'kliente', '{nr}' => (string) $o->get_order_number(), '{avpn}' => $avpn, '{suma}' => self::eur( $o->get_total() ), '{adresas}' => $s['adresas'], '{valandos}' => $s['valandos'], '{tel}' => '+370 681 87787' );\n\t\t$tekstas = preg_replace( \"/\\n{3,}/\", \"\\n\\n\", trim( strtr( $s['iv_tekstas'], $z ) ) ); $h = ''; foreach ( preg_split( \"/\\n\\s*\\n/\", $tekstas ) as $p ) { $p = trim( $p ); if ( '' !== $p ) { $h .= '<p>' . nl2br( esc_html( $p ) ) . '</p>'; } }\n\t\t$pdf = (string) $o->get_meta( '_petshop_completed_pdf' ); $priedai = ( $pdf && file_exists( $pdf ) ) ? array( $pdf ) : array();\n\t\t$tema = strtr( $s['iv_tema'], $z ); $mailer = WC()->mailer(); $ok = (bool) $mailer->send( $el, $tema, $mailer->wrap_message( $tema, $h ), '', $priedai );\n\t\treturn $ok ? 'išsiųstas (' . $el . ( $priedai ? ', su PDF' : ', BE PDF — sąskaitos failo nėra' ) . ')' : 'laiško išsiųsti NEPAVYKO';\n\t}\n")
rep("$s[ $k ] = in_array( $k, array( 'tema', 'adresas', 'valandos' ), true ) ? sanitize_text_field( $v ) : sanitize_textarea_field( $v );",
    "$s[ $k ] = in_array( $k, array( 'tema', 'adresas', 'valandos', 'iv_tema' ), true ) ? sanitize_text_field( $v ) : sanitize_textarea_field( $v );")
rep("\t\t\t. '<label>Darbo laikas ({valandos})<br><input type=\"text\" name=\"valandos\" value=\"' . esc_attr( $s['valandos'] ) . '\"></label>'\n",
    "\t\t\t. '<label>Darbo laikas ({valandos})<br><input type=\"text\" name=\"valandos\" value=\"' . esc_attr( $s['valandos'] ) . '\"></label>'\n\t\t\t. '<p class=\"pilkas maz\">Po „Klientas atsiėmė“ — laiškas su PVM sąskaitos PDF (WC „įvykdytas“ laiškas atsiėmimui nesiunčiamas). Vietaženkliai: {vardas} {nr} {avpn} {suma}.</p>'\n\t\t\t. '<label>Atsiėmė — tema<br><input type=\"text\" name=\"iv_tema\" value=\"' . esc_attr( $s['iv_tema'] ) . '\"></label>'\n\t\t\t. '<label>Atsiėmė — tekstas<br><textarea name=\"iv_tekstas\" rows=\"5\">' . esc_textarea( $s['iv_tekstas'] ) . '</textarea></label>'\n")
rep("Siunčia darbuotojas — skydelio „Paruošta atsiimti“ (varnelė „nesiųsti“). Vietaženkliai:", "Laiškas „paruošta atsiimti“ — siunčia darbuotojas skydelio mygtuku (varnelė „nesiųsti“). Vietaženkliai:")
open('/home/claude/ps/petshop-darbalaukis-v3351.php','w',encoding='utf-8').write(s)
r=subprocess.run(['php','-l','/home/claude/ps/petshop-darbalaukis-v3351.php'],capture_output=True,text=True); print(r.stdout.strip())
if 'No syntax errors' not in r.stdout: sys.exit(1)
print('bytes',len(s.encode()),'md5',hashlib.md5(s.encode()).hexdigest())
