<?php
/** TEMP PS S1618 run e7s — S: Playwright kadrai — langas „Naujas užsakymas“ (tuščias + užpildytas per JS: klientas iš paieškos, prekė iš paieškos, paštomatas), eilių juosta su nuoroda. */
add_action('init', function(){
  if (!isset($_GET['ps_e7s'])) return;
  $o=array('v'=>'S1618 e7s'); global $wpdb; $p=$wpdb->prefix;
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $tu=get_user_by('login','testuotojas'); $uid=$tu->ID; $exp=time()+1800; $tok=WP_Session_Tokens::get_instance($uid)->create($exp);
  $o['cookies']=array(array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok)),array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok)),array('name'=>LOGGED_IN_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'logged_in',$tok)));
  $u=admin_url('admin.php?page=ps-desk&view=naujas');
  $o['shots']=array(
    array('n'=>'s1618_e5_naujas_tuscias','u'=>$u,'w'=>1440,'h'=>1000,'full'=>true,'eval'=>'(function(){return {forma:!!document.getElementById("dlNu"),prist:Array.from(document.querySelectorAll("#nuPrist option")).map(function(o){return o.textContent;}),kaina:document.getElementById("nuPristK").value,pristN:document.getElementById("nuPristN").textContent};})()'),
    array('n'=>'s1618_e5_naujas_uzpildytas','u'=>$u,'w'=>1440,'h'=>1000,'full'=>true,'eval'=>'(async function(){ var sl=function(ms){return new Promise(function(r){setTimeout(r,ms);});}; var q=document.getElementById("nuKlQ"); q.value="Testas 34"; q.dispatchEvent(new Event("input",{bubbles:true})); await sl(1500); var k=document.querySelector("#nuKlR .dl-nu-k"); if(k) k.click(); var pq=document.getElementById("nuPrQ"); pq.value="exclusion hypo"; pq.dispatchEvent(new Event("input",{bubbles:true})); await sl(1800); var a=document.querySelectorAll("#nuPrR .dl-nu-k"); if(a[0]) a[0].click(); await sl(300); pq.value="HAP žaislas"; pq.dispatchEvent(new Event("input",{bubbles:true})); await sl(1800); a=document.querySelectorAll("#nuPrR .dl-nu-k"); if(a[0]) a[0].click(); await sl(300); var qi=document.querySelector("#nuPrT input[data-f=q]"); if(qi){ qi.value="3"; qi.dispatchEvent(new Event("input",{bubbles:true})); } var nu=document.getElementById("nuNuol"); nu.value="2"; nu.dispatchEvent(new Event("input",{bubbles:true})); document.getElementById("nuNuolP").value="lojalus klientas"; var s=document.getElementById("nuPrist"); s.value="venipak_pastomatas"; s.dispatchEvent(new Event("change",{bubbles:true})); await sl(2500); var vq=document.getElementById("nuVietaQ"); vq.value="Nemenčinė"; vq.dispatchEvent(new Event("input",{bubbles:true})); await sl(300); var vs=document.getElementById("nuVietaS"); if(vs.options.length>1) vs.selectedIndex=1; return {klientas:document.querySelector("[name=\\"kl[vardas]\\"]").value+" "+document.querySelector("[name=\\"kl[tel]\\"]").value,prekes:document.querySelectorAll("#nuPrT tbody tr").length,sumos:[document.getElementById("nuS1").textContent,document.getElementById("nuS2").textContent,document.getElementById("nuS3").textContent,document.getElementById("nuS4").textContent],pristN:document.getElementById("nuPristN").textContent,vieta:vs.options[vs.selectedIndex]?vs.options[vs.selectedIndex].textContent:"",vietaN:document.getElementById("nuVietaN").textContent}; })()'),
    array('n'=>'s1618_e5_eiles_juosta','u'=>admin_url('admin.php?page=ps-desk&eile=siandien'),'w'=>1440,'h'=>700,'eval'=>'(function(){var a=document.querySelector(".dl-e-naujas"); return a?a.textContent:"nuorodos nėra";})()'),
  );
  header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE); exit;
},99);
