<?php
/** TEMP PS S1619 run e4d — e3d testai (T0 instancija ON · T1 · T2 · C OFF) su AV preke 19708 (legacy AV, `_stock`; e3d `Petshop_AV_Source::resolve` paieška nerado). D/Q — jau padaryta e3d. */
add_action('init', function(){
  if (!isset($_GET['ps_e4d'])) return;
  $f=strtoupper(sanitize_key($_GET['ps_e4d'])); $o=array('v'=>'S1619 e4d','f'=>$f); global $wpdb; $p=$wpdb->prefix; set_time_limit(280);
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $J=function($o){ header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit; };
  $tu=get_user_by('login','testuotojas'); $uid=$tu->ID; $exp=time()+1800; $tok=WP_Session_Tokens::get_instance($uid)->create($exp); $li=wp_generate_auth_cookie($uid,$exp,'logged_in',$tok);
  $cs=array(new WP_Http_Cookie(array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok))),new WP_Http_Cookie(array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok))),new WP_Http_Cookie(array('name'=>LOGGED_IN_COOKIE,'value'=>$li)));
  $G=function($u,$t=90) use($cs){ return wp_remote_get(html_entity_decode($u,ENT_QUOTES),array('cookies'=>$cs,'timeout'=>$t,'sslverify'=>false,'redirection'=>0)); };
  $eiles=function() use($G){ $r=$G(admin_url('admin.php?page=ps-desk&eile=klausimai')); $h=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'nav'=>mb_substr(trim(preg_replace('/\s+/',' ',wp_strip_all_tags(preg_match('/<main class="dl-main">(.*?)<div class="dl-kortele/su',$h,$mm)?$mm[1]:''))),0,140)); };
  $ping=function() { $r=wp_remote_get(admin_url('admin-ajax.php?action=heartbeat'),array('timeout'=>90,'sslverify'=>false)); $b=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'fatal'=>(int)(stripos($b,'Fatal error')!==false||stripos($b,'Parse error')!==false),'err'=>is_wp_error($r)?$r->get_error_message():''); };
  $inst=function() use($wpdb,$p){ return $wpdb->get_row("SELECT instance_id,is_enabled FROM {$p}woocommerce_shipping_zone_methods WHERE zone_id=1 AND method_id='local_pickup' ORDER BY instance_id LIMIT 1",ARRAY_A); };
  try{
  $_COOKIE[LOGGED_IN_COOKIE]=$li; wp_set_current_user($uid); $n=wp_create_nonce('ps_dl_zurnalas');
  $sk=function($id) use($G,$n){ $r=$G(admin_url('admin-ajax.php?action=ps_dl_skydelis&id='.$id.'&n='.$n),60); return json_decode((string)wp_remote_retrieve_body($r),true)['data']??array(); };
  $skz=function($d){ return array('kur'=>$d['kur']??null,'apmok'=>$d['apmok']??null,'vezejas'=>$d['vezejas']??null,'btn'=>$d['btn']['t']??null,'btn_d'=>mb_substr((string)($d['btn']['d']['tekstas']??''),0,160),'grynais'=>!empty($d['grynais'])?1:0,'red'=>!empty($d['red'])?1:0,'pastaba'=>mb_substr((string)($d['pastaba']??''),0,200),'eil'=>array_map(function($e){return array($e['n'],$e['k'],$e['galimi']??null,array_map(function($z){return $z[0].':'.$z[1];},(array)($e['zing']??array())));},(array)($d['eil']??array())),'takelis'=>array_map(function($t){return $t[0].':'.$t[2];},(array)($d['takelis']??array())),'klausimas'=>$d['klausimas']??null,'dok'=>array_map(function($x){return $x['t'].' '.$x['nr'].(isset($x['bt'])?' ['.$x['bt'].']':'');},(array)($d['dok']??array()))); };
  $uz=function($id){ wp_cache_flush(); $x=wc_get_order($id); if(!$x) return 'NĖRA'; $it=array(); foreach($x->get_items() as $i){ $it[]=array('n'=>mb_substr($i->get_name(),0,30),'q'=>$i->get_quantity(),'src'=>$i->get_meta('_ps_source'),'kelias'=>$i->get_meta('_ps_kelias'),'red'=>$i->get_meta('_reduced_stock'),'av'=>$i->get_meta('_ps_av_reduced_qty')); } $sh=array(); foreach($x->get_items('shipping') as $s){ $sh[]=array($s->get_method_title(),$s->get_method_id(),$s->get_instance_id(),$s->get_total()); }
    return array('st'=>$x->get_status(),'pm'=>$x->get_payment_method(),'pmt'=>$x->get_payment_method_title(),'paid'=>$x->is_paid(),'total'=>$x->get_total(),'avpn'=>$x->get_meta('_petshop_avpn_number'),'pdf'=>basename((string)$x->get_meta('_petshop_completed_pdf')),'rus'=>$x->get_meta('_ps_rusiuota'),'surinkta'=>$x->get_meta('_ps_surinkta'),'ats'=>$x->get_meta('_ps_atsiemimas'),'iss'=>$x->get_meta('_ps_dalys_issiusta'),'be_siuntu'=>$x->get_meta('_ps_uzbaigti_be_siuntu'),'ship'=>$sh,'items'=>$it); };
  $klik=function($u) use($G){ $r=$G($u,120); $loc=(string)wp_remote_retrieve_header($r,'location'); parse_str((string)parse_url($loc,PHP_URL_QUERY),$q); return array('code'=>wp_remote_retrieve_response_code($r),'pd_ok'=>$q['pd_ok']??null,'pd'=>$q['pd_nr']??null,'body'=>mb_substr(wp_strip_all_tags((string)wp_remote_retrieve_body($r)),0,140)); };
  $post=function($body) use($cs){ $r=wp_remote_post(admin_url('admin-post.php'),array('cookies'=>$cs,'timeout'=>120,'sslverify'=>false,'redirection'=>0,'body'=>$body)); $loc=(string)wp_remote_retrieve_header($r,'location'); parse_str((string)parse_url($loc,PHP_URL_QUERY),$q2); return array('code'=>wp_remote_retrieve_response_code($r),'pd_ok'=>$q2['pd_ok']??null,'pd'=>$q2['pd_nr']??null,'eile'=>$q2['eile']??null,'id'=>(int)($q2['atidaryti']??0)); };
  $av_preke=function(){ $x=wc_get_product(19708); return ($x&&$x->get_stock_quantity()>1)?19708:0; };
  if($f==='Q'){ $o['eiles_po']=$eiles(); $o['versija']=class_exists('Petshop_Darbalaukis')?Petshop_Darbalaukis::VERSIJA:'NĖRA'; $o['md5']=md5_file(WPMU_PLUGIN_DIR.'/petshop-darbalaukis.php'); $o['inst']=$inst(); $o['dev_pastas']=count((array)get_option('ps_dev_pastas_zurnalas',array())); $J($o); }
  if($f==='T0'){ $i=$inst(); if($i){ $wpdb->update("{$p}woocommerce_shipping_zone_methods",array('is_enabled'=>1),array('instance_id'=>(int)$i['instance_id'])); WC_Cache_Helper::get_transient_version('shipping',true); } $o['inst']=$inst();
    $r=$G(admin_url('admin.php?page=ps-desk&view=naujas')); $h=(string)wp_remote_retrieve_body($r); $o['forma']=array('code'=>wp_remote_retrieve_response_code($r),'prist_opts'=>preg_match_all('/<select name="prist"[^>]*>(.*?)<\/select>/su',$h,$so)?array_values(array_map('trim',array_map('wp_strip_all_tags',preg_split('/<\/option>/',$so[1][0],-1,PREG_SPLIT_NO_EMPTY)))):array(),'pm'=>preg_match('/data-pm="([^"]+)"/',$h,$pmm)?array_keys((array)json_decode(html_entity_decode($pmm[1]),true)):null);
    $r=$G(admin_url('admin.php?page=ps-desk&view=saskaitos')); $h=(string)wp_remote_retrieve_body($r); $o['saskaitos_sabl']=array('ats_forma'=>(int)preg_match('/name="action" value="ps_dl_ats_sablonas"/',$h),'summary'=>preg_match_all('/<summary>(.*?)<\/summary>/su',$h,$sm)?array_map('wp_strip_all_tags',$sm[1]):array()); $o['av_preke']=$av_preke(); $J($o); }
  if($f==='T1'||$f==='T2'){
    $avp=$av_preke(); if(!$avp){ $o['STOP']='AV prekės nerasta'; $J($o); } $pp=wc_get_product($avp); $o['av_preke']=array('id'=>$avp,'n'=>$pp->get_name(),'stock'=>$pp->get_stock_quantity(),'av'=>class_exists('Petshop_AV_Stock')?Petshop_AV_Stock::qty($avp):null);
    $pr=array(array('id'=>$avp,'q'=>1,'kaina'=>number_format((float)wc_get_price_including_tax($pp),2,'.',''))); if($f==='T1'){ $hp=wc_get_product(35357); $pr[]=array('id'=>35357,'q'=>1,'kaina'=>number_format((float)wc_get_price_including_tax($hp),2,'.','')); }
    $body=array('action'=>'ps_dl_naujas','_wpnonce'=>wp_create_nonce('ps_dl_naujas'),'kl'=>array('uid'=>'0','vardas'=>'ATSIEMIMAS','pavarde'=>'Testas S1619','tel'=>'+37060000097','el'=>'atsiemimas.s1619@dev.avesa.lt','imone'=>'','adresas'=>'','miestas'=>'','kodas'=>''),'pr'=>$pr,'prist'=>'av','prist_kaina'=>'0.00','vieta'=>'','nuolaida'=>'0','nuolaida_pastaba'=>'','pastaba'=>'TEST S1619 '.$f.' atsiėmimas','mok'=>$f==='T1'?'grynais':'pavedimu');
    $z0=count((array)get_option('ps_dev_pastas_zurnalas',array())); $o['post']=$post($body); $id=$o['post']['id']; if(!$id){ $J($o); } $o['id']=$id; $o['uzs']=$uz($id); $d=$sk($id); $o['sk']=$skz($d);
    if($f==='T2'){
      if(empty($d['grynais'])){ $o['STOP']='grynais nuorodos nėra'; $J($o); }
      $o['grynais']=$klik($d['grynais']); $o['uzs_po_grynais']=$uz($id); $d=$sk($id); $o['sk_po_grynais']=$skz($d);
      if(($d['btn']['t']??'')==='Surinkti'){ $r=$G($d['btn']['u'],120); $o['lapai']=array('code'=>wp_remote_retrieve_response_code($r),'b'=>strlen((string)wp_remote_retrieve_body($r))); wp_cache_flush(); $o['surinkta']=wc_get_order($id)->get_meta('_ps_surinkta'); $d=$sk($id); $o['sk_po_lapu']=$skz($d); } else { $o['STOP']='btn ne Surinkti: '.($d['btn']['t']??'-'); $J($o); }
      if(($d['btn']['t']??'')==='Paruošta atsiimti'){ $o['paruosta']=$klik($d['btn']['u']); $o['uzs_po_paruosta']=$uz($id); $d=$sk($id); $o['sk_po_paruosta']=$skz($d); } else { $o['STOP']='btn ne Paruošta: '.($d['btn']['t']??'-'); $J($o); }
      if(($d['btn']['t']??'')==='Klientas atsiėmė'){ $o['atsieme']=$klik($d['btn']['u']); $o['uzs_po_atsieme']=$uz($id); $d=$sk($id); $o['sk_po_atsieme']=$skz($d); } else { $o['STOP']='btn ne Atsiėmė: '.($d['btn']['t']??'-'); }
    }
    $notes=wc_get_order_notes(array('order_id'=>$id,'limit'=>7)); $o['pastabos']=array_map(function($nn){return mb_substr($nn->content,0,200);},$notes);
    $z=(array)get_option('ps_dev_pastas_zurnalas',array()); $o['dev_pastas']=array('pries'=>$z0,'po'=>count($z),'nauji'=>array_map(function($e){return array(mb_substr($e['tema']??'',0,90),$e['kam']??($e['to']??''),$e['priedai']??null,mb_substr(wp_strip_all_tags((string)($e['tekstas']??($e['body']??''))),0,400));},array_slice($z,$z0)));
    $o['eiles']=$eiles(); $J($o);
  }
  if($f==='C'){ $i=$inst(); if($i){ $wpdb->update("{$p}woocommerce_shipping_zone_methods",array('is_enabled'=>0),array('instance_id'=>(int)$i['instance_id'])); WC_Cache_Helper::get_transient_version('shipping',true); } $o['inst']=$inst(); $r=$G(admin_url('admin.php?page=ps-desk&view=naujas')); $h=(string)wp_remote_retrieve_body($r); $o['forma_av_yra']=(int)preg_match('/Atsiėmimas AV/u',$h); $o['eiles']=$eiles(); $o['temp_liko']=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$p}snippets WHERE name LIKE 'TEMP%'"); $J($o); }
  }catch(Throwable $e){ $o['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $J($o);
},99);
