<?php
/** TEMP PS S1628 run e22d — petshop-klientui.php v1.0 → v1.0.1 (front-end visiems tik sąskaita; md5 96ee85d5b669dc78a38642dcc6e8379f → ccf9032d78416e805d90993b7fe1def1); po deploy — admin (uid 1) „ačiū“ puslapis #35826 ir klientas #5787: mygtukų sk. */
add_action('init', function(){
  if (!isset($_GET['ps_e22d'])) return;
  $o=array('v'=>'S1628 e22d'); global $wpdb; $p=$wpdb->prefix; set_time_limit(200);
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $J=function($o){ header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit; };
  $ping=function(){ $r=wp_remote_get(admin_url('admin-ajax.php?action=heartbeat'),array('timeout'=>90,'sslverify'=>false)); $b=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'fatal'=>(int)(stripos($b,'Fatal error')!==false||stripos($b,'Parse error')!==false),'err'=>is_wp_error($r)?$r->get_error_message():''); };
  $F=array(
    array('f'=>'petshop-klientui.php','buvo'=>'96ee85d5b669dc78a38642dcc6e8379f','md5'=>'ccf9032d78416e805d90993b7fe1def1','bk'=>'petshop-klientui-v10-BACKUP-','b64'=>'PD9waHAKLyoqCiAqIFBldHNob3AgS2xpZW50dWkgdjEuMC4xIChTMTYyOCwgUmFpbWlvIGthZHJhczogcHJpc2lqdW5nxJlzIGthaXAgYWRtaW5pc3RyYXRvcml1cyDigJ5hxI1pxavigJwgcHVzbGFweWplIG1hdMSXIHZpc3VzIDQgbXlndHVrdXMg4oCUIHYxLjAgZGFyYnVvdG9qYW1zIHBhbGlrbyB2aXNrxIUpOgogKiAgIGZyb250LWVuZCdlICh1xb5zYWt5bW8sIOKAnmHEjWnFq+KAnCwgcGFza3lyb3MgcHVzbGFwaWFpLCBgcHJpbnQtb3JkZXJgIGVuZHBvaW50J2FzKSDigJQgVklTSUVNUyB0aWsgYGludm9pY2VgLCBuZXByaWtsYXVzb21haSBudW8gdGVpc2nFszsgYWRtaW4nYXMgaXIgYHdwX2FqYXhfcHJpbnRfb3JkZXJgIOKAlCBrYWlwIGJ1dm8uCiAqIFBldHNob3AgS2xpZW50dWkgdjEuMCAoUzE2MjgsIFJhaW1pcyAwOS0wNjog4oCea2xpZW50dWkgcmVpa2lhIHRpayBzxIVza2FpdG9zLCBvIGt2aXTFsyBpciB2YcW+dGFyYcWhxI1pxbMgdGlrcmFpIG5lcmVpa2lh4oCcKQogKgogKiBLQVM6IFdDRE4gKFdvb0NvbW1lcmNlIFByaW50IEludm9pY2UgJiBEZWxpdmVyeSBOb3RlcyA3LjMpIGtsaWVudG8gcHVzxJdqZSDigJQgcGFza3lyb3MgdcW+c2FreW3FsyBzxIVyYcWhZSwgdcW+c2FreW1vCiAqIHB1c2xhcHlqZSBpciDigJ5hxI1pxavigJwgcHVzbGFweWplIOKAlCByb2RvIHBvIG15Z3R1a8SFIGtpZWt2aWVuYW0gxK9qdW5ndGFtIMWhYWJsb251aTog4oCeU3BhdXNkaW50aSBzxIVza2FpdMSF4oCcLCDigJ5TcGF1c2RpbnRpIGt2aXTEheKAnCwKICog4oCeU3BhdXNkaW50aSB2YcW+dGFyYcWhdMSv4oCcIChkZWxpdmVyeS1ub3RlKSBpciBkYXIga2FydMSFIOKAnlNwYXVzZGludGkgdmHFvnRhcmHFoXTEr+KAnCAocGFja2luZy1zbGlwKS4gS2xpZW50dWkgcmVpa2lhIHRpayBQVk0gc8SFc2thaXRvcy4KICoKICogS0FJUDogV0NETiBmaWx0cmFzIGB3Y2RuX3RlbXBsYXRlX3R5cGVzX2Zyb21fb3JkZXJgIChoZWxwZXJzL2NsYXNzLXV0aWxzLnBocCBgZ2V0X3RlbXBsYXRlX3R5cGVzKClgLCBuYXVkb2phbWFzIGlyIG15Z3R1a2FtcywKICogaXIgYHByaW50LW9yZGVyYCBlbmRwb2ludCd1aSkg4oCUIG5lIGFkbWluaXN0cmF0b3JpdWkgKGZyb250LWVuZCwgYmUgYGVkaXRfc2hvcF9vcmRlcnNgKSBwYWxpZWthbWFzIFRJSyBgaW52b2ljZWAuCiAqIEFkbWluJ2UgKFdDIHXFvnNha3ltbyBsYW5nYXMsIGB3cF9hamF4X3ByaW50X29yZGVyYCkgaXIgZGFyYnVvdG9qYW1zIOKAlCB2aXNrYXMga2FpcCBidXZvLiDFoGFibG9uYWkgV0NETiBudXN0YXR5bXVvc2UgbmVpxaFqdW5naWFtaQogKiAoZGFyYnVvdG9qxbMgc3BhdXNkaW5pbXVpIGxpZWthKS4gS2xpZW50byBwYXNreXJvcyDigJ5BdHNpc2FreXRpIHN1dGFydGllcyAoRVMgMTQgZC4gdGVpc8SXKeKAnCDigJQgYHBldHNob3AtYXRzaXNha3ltYXMucGhwYCwgbmVsaWVzdGEuCiAqLwppZiAoICEgZGVmaW5lZCggJ0FCU1BBVEgnICkgKSB7IGV4aXQ7IH0KCmFkZF9maWx0ZXIoICd3Y2RuX3RlbXBsYXRlX3R5cGVzX2Zyb21fb3JkZXInLCBmdW5jdGlvbiAoICR0eXBlcywgJG9yZGVyICkgewoJaWYgKCBpc19hZG1pbigpICkgeyByZXR1cm4gJHR5cGVzOyB9IC8vIFdDIGFkbWluIGxhbmdhcyBpciBgd3BfYWpheF9wcmludF9vcmRlcmAg4oCUIGRhcmJ1b3RvamFtcyB2aXNrYXMKCXJldHVybiBpbl9hcnJheSggJ2ludm9pY2UnLCAoYXJyYXkpICR0eXBlcywgdHJ1ZSApID8gYXJyYXkoICdpbnZvaWNlJyApIDogYXJyYXkoKTsgLy8gdjEuMC4xOiBmcm9udC1lbmQg4oCUIHZpc2llbXMgdGlrIHPEhXNrYWl0YQp9LCAyMCwgMiApOwo='));
  $up=wp_upload_dir(); $bk=trailingslashit($up['basedir']).'ps-backups'; wp_mkdir_p($bk); $done=array();
  try{
  foreach($F as $x){ $c=base64_decode($x['b64'],true); if($c===false||md5($c)!==$x['md5']){ $o['STOP']=$x['f'].' b64/md5'; break; }
    try { token_get_all($c, TOKEN_PARSE); } catch (Throwable $e) { $o['STOP']=$x['f'].' token: '.$e->getMessage(); break; }
    $t=WPMU_PLUGIN_DIR.'/'.$x['f']; $b=md5_file($t); if($b!==$x['buvo']){ $o['STOP']=$x['f'].' gyvas nežinomas '.$b; break; }
    $bkf=$bk.'/'.$x['bk'].date('Y-m-d').'.php'; copy($t,$bkf); $o[$x['f']]=array('backup'=>basename($bkf),'rasyta'=>file_put_contents($t,$c),'po'=>md5_file($t)); if(function_exists('opcache_invalidate')){ @opcache_invalidate($t,true); } $done[]=array($t,$bkf);
    $o[$x['f']]['ping']=$ping(); if($o[$x['f']]['ping']['fatal']||$o[$x['f']]['ping']['code']>=500||$o[$x['f']]['ping']['err']){ foreach($done as $dd){ copy($dd[1],$dd[0]); } $o['ATKURTA']='visi atkurti'; break; } }
  $kl=function($uid,$u) { $exp=time()+600; $tok=WP_Session_Tokens::get_instance($uid)->create($exp); $cs=array(new WP_Http_Cookie(array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok))),new WP_Http_Cookie(array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok))),new WP_Http_Cookie(array('name'=>LOGGED_IN_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'logged_in',$tok)))); $r=wp_remote_get($u,array('cookies'=>$cs,'timeout'=>90,'sslverify'=>false,'redirection'=>2)); $h=(string)wp_remote_retrieve_body($r); preg_match_all('/class="button print"[^>]*>\s*([^<]+?)\s*<\/a>/u',$h,$m); return array('code'=>wp_remote_retrieve_response_code($r),'mygtukai'=>array_map('trim',$m[1])); };
  $x=wc_get_order(35826); $aciu=$x?$x->get_checkout_order_received_url():''; $o['aciu_url']=mb_substr($aciu,0,80);
  $o['admin_aciu']=$kl(1,$aciu); $o['klientas_aciu']=$kl(5787,$aciu); $o['klientas_view']=$kl(5787,wc_get_endpoint_url('view-order',35826,wc_get_page_permalink('myaccount'))); $o['inga_aciu']=$kl(5788,$aciu);
  $o['versijos']=array('klientui'=>md5_file(WPMU_PLUGIN_DIR.'/petshop-klientui.php'));
  }catch(Throwable $e){ $o['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $J($o);
},99);
