<?php
/** TEMP PS S1628 run e21d — naujas mu-plugin `petshop-klientui.php` v1.0 (WCDN mygtukai klientui — tik sąskaita) — sukūrimas (md5 96ee85d5b669dc78a38642dcc6e8379f, token_get_all, ping → rollback = failo pašalinimas) · T: kliento (#5787) užsakymo puslapis #35826 ir paskyros sąrašas — mygtukų sk. prieš/po; admin'o užsakymo langas nekeistas. */
add_action('init', function(){
  if (!isset($_GET['ps_e21'])) return;
  $f=strtoupper(sanitize_key($_GET['ps_e21'])); $o=array('v'=>'S1628 e21','f'=>$f); global $wpdb; $p=$wpdb->prefix; set_time_limit(200);
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $J=function($o){ header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit; };
  $ping=function(){ $r=wp_remote_get(admin_url('admin-ajax.php?action=heartbeat'),array('timeout'=>90,'sslverify'=>false)); $b=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'fatal'=>(int)(stripos($b,'Fatal error')!==false||stripos($b,'Parse error')!==false),'err'=>is_wp_error($r)?$r->get_error_message():''); };
  $kl=function($uid,$u) { $exp=time()+600; $tok=WP_Session_Tokens::get_instance($uid)->create($exp); $cs=array(new WP_Http_Cookie(array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok))),new WP_Http_Cookie(array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok))),new WP_Http_Cookie(array('name'=>LOGGED_IN_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'logged_in',$tok)))); $r=wp_remote_get($u,array('cookies'=>$cs,'timeout'=>90,'sslverify'=>false,'redirection'=>2)); $h=(string)wp_remote_retrieve_body($r); preg_match_all('/class="button print"[^>]*>\s*([^<]+?)\s*<\/a>/u',$h,$m); return array('code'=>wp_remote_retrieve_response_code($r),'mygtukai'=>array_map('trim',$m[1]),'atsisakymas'=>(int)(strpos($h,'Atsisakyti sutarties')!==false),'sarase'=>preg_match_all('/wcdn_print_[a-z_-]+/',$h,$mm)?array_values(array_unique($mm[0])):array()); };
  try{
  $t=WPMU_PLUGIN_DIR.'/petshop-klientui.php';
  if($f==='D'){
    $o['pries_klientas']=$kl(5787,wc_get_endpoint_url('view-order',35826,wc_get_page_permalink('myaccount'))); $o['pries_sarasas']=$kl(5787,wc_get_endpoint_url('orders','',wc_get_page_permalink('myaccount')));
    $c=base64_decode('PD9waHAKLyoqCiAqIFBldHNob3AgS2xpZW50dWkgdjEuMCAoUzE2MjgsIFJhaW1pcyAwOS0wNjog4oCea2xpZW50dWkgcmVpa2lhIHRpayBzxIVza2FpdG9zLCBvIGt2aXTFsyBpciB2YcW+dGFyYcWhxI1pxbMgdGlrcmFpIG5lcmVpa2lh4oCcKQogKgogKiBLQVM6IFdDRE4gKFdvb0NvbW1lcmNlIFByaW50IEludm9pY2UgJiBEZWxpdmVyeSBOb3RlcyA3LjMpIGtsaWVudG8gcHVzxJdqZSDigJQgcGFza3lyb3MgdcW+c2FreW3FsyBzxIVyYcWhZSwgdcW+c2FreW1vCiAqIHB1c2xhcHlqZSBpciDigJ5hxI1pxavigJwgcHVzbGFweWplIOKAlCByb2RvIHBvIG15Z3R1a8SFIGtpZWt2aWVuYW0gxK9qdW5ndGFtIMWhYWJsb251aTog4oCeU3BhdXNkaW50aSBzxIVza2FpdMSF4oCcLCDigJ5TcGF1c2RpbnRpIGt2aXTEheKAnCwKICog4oCeU3BhdXNkaW50aSB2YcW+dGFyYcWhdMSv4oCcIChkZWxpdmVyeS1ub3RlKSBpciBkYXIga2FydMSFIOKAnlNwYXVzZGludGkgdmHFvnRhcmHFoXTEr+KAnCAocGFja2luZy1zbGlwKS4gS2xpZW50dWkgcmVpa2lhIHRpayBQVk0gc8SFc2thaXRvcy4KICoKICogS0FJUDogV0NETiBmaWx0cmFzIGB3Y2RuX3RlbXBsYXRlX3R5cGVzX2Zyb21fb3JkZXJgIChoZWxwZXJzL2NsYXNzLXV0aWxzLnBocCBgZ2V0X3RlbXBsYXRlX3R5cGVzKClgLCBuYXVkb2phbWFzIGlyIG15Z3R1a2FtcywKICogaXIgYHByaW50LW9yZGVyYCBlbmRwb2ludCd1aSkg4oCUIG5lIGFkbWluaXN0cmF0b3JpdWkgKGZyb250LWVuZCwgYmUgYGVkaXRfc2hvcF9vcmRlcnNgKSBwYWxpZWthbWFzIFRJSyBgaW52b2ljZWAuCiAqIEFkbWluJ2UgKFdDIHXFvnNha3ltbyBsYW5nYXMsIGB3cF9hamF4X3ByaW50X29yZGVyYCkgaXIgZGFyYnVvdG9qYW1zIOKAlCB2aXNrYXMga2FpcCBidXZvLiDFoGFibG9uYWkgV0NETiBudXN0YXR5bXVvc2UgbmVpxaFqdW5naWFtaQogKiAoZGFyYnVvdG9qxbMgc3BhdXNkaW5pbXVpIGxpZWthKS4gS2xpZW50byBwYXNreXJvcyDigJ5BdHNpc2FreXRpIHN1dGFydGllcyAoRVMgMTQgZC4gdGVpc8SXKeKAnCDigJQgYHBldHNob3AtYXRzaXNha3ltYXMucGhwYCwgbmVsaWVzdGEuCiAqLwppZiAoICEgZGVmaW5lZCggJ0FCU1BBVEgnICkgKSB7IGV4aXQ7IH0KCmFkZF9maWx0ZXIoICd3Y2RuX3RlbXBsYXRlX3R5cGVzX2Zyb21fb3JkZXInLCBmdW5jdGlvbiAoICR0eXBlcywgJG9yZGVyICkgewoJaWYgKCBpc19hZG1pbigpICYmICEgd3BfZG9pbmdfYWpheCgpICkgeyByZXR1cm4gJHR5cGVzOyB9CglpZiAoIGN1cnJlbnRfdXNlcl9jYW4oICdlZGl0X3Nob3Bfb3JkZXJzJyApICkgeyByZXR1cm4gJHR5cGVzOyB9CglyZXR1cm4gaW5fYXJyYXkoICdpbnZvaWNlJywgKGFycmF5KSAkdHlwZXMsIHRydWUgKSA/IGFycmF5KCAnaW52b2ljZScgKSA6IGFycmF5KCk7Cn0sIDIwLCAyICk7Cg==',true); if($c===false||md5($c)!=='96ee85d5b669dc78a38642dcc6e8379f'){ $o['STOP']='b64/md5'; $J($o); }
    try { token_get_all($c, TOKEN_PARSE); } catch (Throwable $e) { $o['STOP']='token: '.$e->getMessage(); $J($o); }
    if(file_exists($t)){ $o['STOP']='failas jau yra '.md5_file($t); $J($o); }
    $o['rasyta']=file_put_contents($t,$c); $o['po']=md5_file($t); if(function_exists('opcache_invalidate')){ @opcache_invalidate($t,true); }
    $o['ping']=$ping(); if($o['ping']['fatal']||$o['ping']['code']>=500||$o['ping']['err']){ @unlink($t); $o['ATKURTA']='failas pašalintas'; $J($o); }
    $o['po_klientas']=$kl(5787,wc_get_endpoint_url('view-order',35826,wc_get_page_permalink('myaccount'))); $o['po_sarasas']=$kl(5787,wc_get_endpoint_url('orders','',wc_get_page_permalink('myaccount')));
    $o['po_darbuotojas_view']=$kl(75,wc_get_endpoint_url('view-order',35826,wc_get_page_permalink('myaccount')));
    $J($o); }
  }catch(Throwable $e){ $o['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $J($o);
},99);
