<?php
/** TEMP PS S1625 run e17t — TIKRI Venipak testai (Raimis: „aš paskui Venipak ištrinsiu“): 1 — AV užs. 19475×2 → Surinkti → Lipdukas su dėžių sk. 2 → `_ps_siuntos` numerių sk., lipduko PDF (siuntėjas be vardo); 2 — du VF dropship → kortelės „Lipdukai (2)“ → „Užsakyti iš VF (2 užs.)“ su lipdukais ir prierašu → laiškas terra@ IŠLEISTAS (dev-pastas v1.2); 3 — vidinė pastaba (AJAX) #35821. LP nenaudojamas. */
add_action('init', function(){
  if (!isset($_GET['ps_e17'])) return;
  $f=strtoupper(sanitize_key($_GET['ps_e17'])); $o=array('v'=>'S1625 e17t','f'=>$f); global $wpdb; $p=$wpdb->prefix; set_time_limit(290);
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $J=function($o){ header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit; };
  $tu=get_user_by('login','testuotojas'); $uid=$tu->ID; $exp=time()+1800; $tok=WP_Session_Tokens::get_instance($uid)->create($exp); $li=wp_generate_auth_cookie($uid,$exp,'logged_in',$tok);
  $cs=array(new WP_Http_Cookie(array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok))),new WP_Http_Cookie(array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok))),new WP_Http_Cookie(array('name'=>LOGGED_IN_COOKIE,'value'=>$li)));
  $G=function($u,$t=90) use($cs){ return wp_remote_get(html_entity_decode($u,ENT_QUOTES),array('cookies'=>$cs,'timeout'=>$t,'sslverify'=>false,'redirection'=>0)); };
  $eiles=function() use($G){ $r=$G(admin_url('admin.php?page=ps-desk&eile=visi')); $h=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'nav'=>mb_substr(trim(preg_replace('/\s+/',' ',wp_strip_all_tags(preg_match('/<div class="dl-eiles">(.*?)<\/div>/su',$h,$mm)?$mm[1]:''))),0,140),'warning'=>substr_count($h,'<b>Warning</b>')); };
  $_COOKIE[LOGGED_IN_COOKIE]=$li; wp_set_current_user($uid); $n=wp_create_nonce('ps_dl_zurnalas');
  $sk=function($id) use($G,$n){ $r=$G(admin_url('admin-ajax.php?action=ps_dl_skydelis&id='.$id.'&n='.$n),60); return json_decode((string)wp_remote_retrieve_body($r),true)['data']??array(); };
  $skz=function($d){ return array('kur'=>$d['kur']??null,'btn'=>$d['btn']['t']??null,'eil'=>array_map(function($e){return $e['k'].($e['bukle']?' ('.$e['bukle'].')':'');},(array)($d['eil']??array()))); };
  $klik=function($u) use($G){ $r=$G($u,150); $loc=(string)wp_remote_retrieve_header($r,'location'); parse_str((string)parse_url($loc,PHP_URL_QUERY),$q); return array('code'=>wp_remote_retrieve_response_code($r),'pd_ok'=>$q['pd_ok']??null,'pd'=>mb_substr((string)($q['pd_nr']??''),0,160)); };
  $post=function($body) use($cs){ $r=wp_remote_post(admin_url('admin-post.php'),array('cookies'=>$cs,'timeout'=>150,'sslverify'=>false,'redirection'=>0,'body'=>$body)); $loc=(string)wp_remote_retrieve_header($r,'location'); parse_str((string)parse_url($loc,PHP_URL_QUERY),$q2); return array('code'=>wp_remote_retrieve_response_code($r),'pd_ok'=>$q2['pd_ok']??null,'pd'=>mb_substr((string)($q2['pd_nr']??''),0,160),'id'=>(int)($q2['atidaryti']??0)); };
  $uz=function($id){ wp_cache_flush(); $x=wc_get_order($id); if(!$x) return 'NĖRA'; return array('st'=>$x->get_status(),'paid'=>$x->is_paid(),'total'=>$x->get_total(),'avpn'=>$x->get_meta('_petshop_avpn_number'),'iss'=>$x->get_meta('_ps_dalys_issiusta'),'siuntos'=>class_exists('Petshop_Siuntos')?Petshop_Siuntos::sarasas($id):null); };
  $nauj=function($prekes,$vardas,$pastaba) { $ord=wc_create_order(array('customer_id'=>5787,'created_via'=>'checkout')); $adr=array('first_name'=>'E2E','last_name'=>$vardas,'address_1'=>'Gedimino pr. 1','city'=>'Vilnius','postcode'=>'01103','country'=>'LT','email'=>'s1609.klientas@avesa.lt','phone'=>'+37060000099'); $ord->set_address($adr,'billing'); unset($adr['email'],$adr['phone']); $ord->set_address($adr,'shipping'); foreach($prekes as $pr){ $ord->add_product(wc_get_product($pr[0]),$pr[1]); } $sh=new WC_Order_Item_Shipping(); $sh->set_method_id('shopup_venipak_shipping_courier_method'); $sh->set_instance_id(2); $sh->set_method_title('VENIPAK Kurjeris'); $sh->set_total(3.297521); $ord->add_item($sh); $ord->set_payment_method('bacs'); $ord->set_payment_method_title('Bankinis pavedimas'); $ord->set_customer_note($pastaba); $ord->calculate_totals(); $ord->save(); $id=$ord->get_id(); $ord->payment_complete(); return $id; };
  $lipdukas=function($id,$sandelis,$nr) { $x=wc_get_order($id); $x->update_meta_data('venipak_shipping_order_data',wp_json_encode(array('pack_numbers'=>array($nr),'manifest'=>'07267260906E2E'))); $x->save(); return Petshop_Siuntos::prideti_is_plugino($id,$sandelis,'E2E'); }; // fiktyvus, Venipak nekviečiamas
  $zingsnis=function($id,$laukiu) use($sk,$skz,$klik,$uz,&$o){ wp_cache_flush(); $d=$sk($id); $z=$skz($d); if(($d['btn']['t']??'')!==$laukiu){ $o['STOP']='#'.$id.' laukiau „'.$laukiu.'“, yra „'.($d['btn']['t']??'-').'“ ('.$z['kur'].')'; return null; } $r=$klik($d['btn']['u']); wp_cache_flush(); return array('mygtukas'=>$laukiu,'r'=>$r,'po'=>$skz($sk($id)),'uzs'=>$uz($id)); };
  $forma=function($h,$id){ if(!preg_match('/<form[^>]*id="'.$id.'"[^>]*>(.*?)<\/form>/su',$h,$m)) return null; preg_match_all('/<input[^>]*name="([^"]+)"[^>]*value="([^"]*)"/u',$m[1],$ii,PREG_SET_ORDER); $in=array(); foreach($ii as $x){ $in[$x[1]]=html_entity_decode($x[2],ENT_QUOTES); } preg_match_all('/<button[^>]*>(.*?)<\/button>/su',$m[1],$bb); return array('in'=>$in,'btn'=>array_map(function($b){return trim(wp_strip_all_tags($b));},$bb[1])); };
  $kortele=function($src) use($G,$forma){ $r=$G(admin_url('admin.php?page=ps-desk&eile=laiskai'),120); $h=(string)wp_remote_retrieve_body($r); $fo=$forma($h,'dlf_'.$src); $ats=''; if(preg_match('/<form[^>]*class="dl-inl dl-ats-f"[^>]*>(.*?)<\/form>/su',substr($h,(int)strpos($h,'Užsakyti iš '.strtoupper($src))),$af)){ preg_match('/name="_wpnonce"[^>]*value="([^"]+)"/',$af[1],$nn); $ats=$nn[1]??''; } return array('forma'=>$fo,'ats_nonce'=>$ats,'antras'=>preg_match('/<p class="pastaba dl-antras">(.*?)<\/p>/su',$h,$am)?wp_strip_all_tags($am[1]):''); };
  try{
  $lipd_href=function($h,$src){ return preg_match('/<a class="v p" href="([^"]+)">Lipdukai \((\d+)\)<\/a>/u',substr($h,(int)strpos($h,'Užsakyti iš '.strtoupper($src))),$m)?array(html_entity_decode($m[1],ENT_QUOTES),(int)$m[2]):null; };
  $pdf=function($id) use($G){ $u=wp_nonce_url(admin_url('admin-post.php?action=ps_dropship_lipdukas&id='.$id),'ps_dropship_lipdukas'); $r=$G($u,120); $b=(string)wp_remote_retrieve_body($r); return array('code'=>wp_remote_retrieve_response_code($r),'ct'=>wp_remote_retrieve_header($r,'content-type'),'n'=>strlen($b),'pdf'=>substr($b,0,4)==='%PDF'?base64_encode($b):null,'tekstas'=>substr($b,0,4)==='%PDF'?'':mb_substr(wp_strip_all_tags($b),0,200)); };
  if($f==='1'){ $o['eiles_pries']=$eiles();
    $id=$nauj(array(array(19475,2)),'Venipak 2 dėžės','VP-1 AV 2 dėžės'); $o['id']=$id; update_option('ps_e17_ids',array_merge((array)get_option('ps_e17_ids',array()),array('1'=>$id)),false);
    $o['surinkti']=$zingsnis($id,'Surinkti'); if(!empty($o['STOP'])) $J($o);
    wp_cache_flush(); $d=$sk($id); if(($d['btn']['t']??'')!=='Lipdukas'){ $o['STOP']='btn ne Lipdukas: '.($d['btn']['t']??'-'); $J($o); }
    $u=$d['btn']['u'].'&n=2'; $o['lipdukas']=$klik($u); wp_cache_flush(); $o['uzs']=$uz($id); $o['sk_po']=$skz($sk($id)); $o['pak']=wc_get_order($id)->get_meta(Petshop_Desk::META_PAK);
    $o['pdf']=$pdf($id); $o['eiles_po']=$eiles(); $J($o); }
  if($f==='2'){ $o['eiles_pries']=$eiles(); $z0=count((array)get_option('ps_dev_pastas_zurnalas',array()));
    $a=35823; $b=35824; $o['ids']=array($a,$b);
    foreach(array($a,$b) as $x){ $d=$sk($x); $u='';foreach((array)($d['eil']??array()) as $e){ foreach((array)$e['keliai'] as $kk){ if('tiesiai'===$kk['k']&&!empty($kk['u'])) $u=$kk['u']; } } $o['kelias_'.$x]=$u?$klik($u):'nėra tiesiai nuorodos ('.json_encode($skz($d)['eil']).')'; }
    wp_cache_flush(); $c=$nauj(array(array(35357,1)),'VP dropship C','VP-2c v3.39.1'); $o['id_c']=$c; $o['sk_c']=$skz($sk($c)); // grynai VF su atvira VF partija → turi būti „siunčia klientui“
    $r=$G(admin_url('admin.php?page=ps-desk&eile=laiskai'),120); $h=(string)wp_remote_retrieve_body($r); $lh=$lipd_href($h,'vf'); $o['lipdukai_mygtukas']=$lh; if(!$lh){ $o['STOP']='nėra Lipdukai (n)'; $o['zingsniai']=preg_match('/<div class="dl-zingsniai-k">(.*?)<form/su',substr($h,(int)strpos($h,'Užsakyti iš VF')),$m)?mb_substr(strip_tags($m[1],'<a><button>'),0,500):''; $J($o); }
    $r1=$G($lh[0],200); $loc=(string)wp_remote_retrieve_header($r1,'location'); $o['lipdukai_1']=array('code'=>wp_remote_retrieve_response_code($r1),'loc'=>mb_substr($loc,0,120));
    if($loc&&strpos($loc,'ps_desk_veiksmas')!==false){ $r2=$G($loc,240); $loc2=(string)wp_remote_retrieve_header($r2,'location'); parse_str((string)parse_url($loc2,PHP_URL_QUERY),$q2); $o['lipdukai_2']=array('code'=>wp_remote_retrieve_response_code($r2),'pd_ok'=>$q2['pd_ok']??null,'pd'=>mb_substr((string)($q2['pd_nr']??''),0,200)); }
    wp_cache_flush(); foreach(array($a,$b,$c) as $x){ $o['siuntos_'.$x]=Petshop_Siuntos::sarasas($x); }
    $r=$G(admin_url('admin.php?page=ps-desk&eile=laiskai'),120); $h=(string)wp_remote_retrieve_body($r); $fo=$forma($h,'dlf_vf'); $o['kortele']=array('btn'=>$fo['btn']??null,'uzsakymai'=>$fo['in']['uzsakymai']??null,'lipduko_zymes'=>substr_count($h,'✓ lipdukas'));
    $o['siusti']=$post(array('action'=>'ps_dl_uzsakyti','_wpnonce'=>$fo['in']['_wpnonce'],'tiekejas'=>'vf','uzsakymai'=>$a.','.$b.','.$c,'ids_av'=>'','ps_dl_g'=>admin_url('admin.php?page=ps-desk&eile=laiskai'),'laisk_zyme'=>'1','laisk_man'=>'1','su_lipdukais'=>'1','su_manifestu'=>'1','pastaba'=>"TESTAS iš dev — prašome nevykdyti.\nPrierašo patikra."));
    wp_cache_flush(); $z=(array)get_option('ps_dev_pastas_zurnalas',array()); $o['dev_pastas_nauji']=array_map(function($e){return ($e['laikas']??'').' '.mb_substr($e['tema']??'',0,80).' → '.($e['kam']??'').' ['.(int)($e['priedai']??0).' '.implode(',',(array)($e['failai']??array())).']';},array_slice($z,$z0));
    $ar=(array)get_option('ps_laisku_archyvas',array()); $o['archyvas']=array('laikas'=>$ar[0]['laikas']??'','tema'=>$ar[0]['tema']??'','kam'=>$ar[0]['kam']??'','priedai'=>$ar[0]['priedai']??null,'prierasas'=>(int)(strpos((string)($ar[0]['html']??''),'TESTAS iš dev')!==false));
    $o['sk_a']=$skz($sk($a)); $o['pdf_a']=$pdf($a); $o['eiles_po']=$eiles(); $J($o); }
  if($f==='3'){ $id=35821; $d=$sk($id); $o['vidine_pries']=array($d['vidine']??null,$d['vidine_kas']??null);
    $r=wp_remote_post(admin_url('admin-ajax.php'),array('cookies'=>$cs,'timeout'=>60,'sslverify'=>false,'body'=>array('action'=>'ps_dl_vidine','id'=>$id,'n'=>$d['vidine_n']??'','tekstas'=>"Paskambinti klientui dėl adreso.\nDėžė trapi — pažymėti.")));
    $o['ajax']=json_decode((string)wp_remote_retrieve_body($r),true); wp_cache_flush(); $x=wc_get_order($id); $o['meta']=array($x->get_meta('_ps_vidine_pastaba'),$x->get_meta('_ps_vidine_pastaba_kas'));
    $d=$sk($id); $o['vidine_po']=array($d['vidine']??null,$d['vidine_kas']??null); $r=$G(admin_url('admin.php?page=ps-desk&eile=visi'),120); $h=(string)wp_remote_retrieve_body($r); $o['sarase_zenklas']=(int)preg_match('/data-id="35821".{0,400}class="dl-vid"/su',$h);
    $o['ivykis']=$wpdb->get_row("SELECT veiksmas,kas_vardas,LEFT(pastaba,80) p FROM {$p}ps_uzsakymu_ivykiai WHERE uzsakymas=35821 AND veiksmas='vidine_pastaba' ORDER BY id DESC LIMIT 1",ARRAY_A); $J($o); }
  if($f==='D'){ $id=35822; $o['id']=$id; $o['opt']=get_option('ps_e17_ids'); $d=$sk($id); $o['btn_u']=$d['btn']['u']??null;
    $r=$G(($d['btn']['u']??'').'&n=2',150); $loc=(string)wp_remote_retrieve_header($r,'location'); $o['klik']=array('code'=>wp_remote_retrieve_response_code($r),'loc'=>mb_substr($loc,0,120));
    if($loc){ $r2=$G($loc,200); $loc2=(string)wp_remote_retrieve_header($r2,'location'); parse_str((string)parse_url($loc2,PHP_URL_QUERY),$q2); $o['klik2']=array('code'=>wp_remote_retrieve_response_code($r2),'loc'=>mb_substr($loc2,0,200),'pd_ok'=>$q2['pd_ok']??null,'pd'=>mb_substr((string)($q2['pd_nr']??''),0,200),'body'=>mb_substr(wp_strip_all_tags((string)wp_remote_retrieve_body($r2)),0,300)); }
    $o['sk_35823']=$skz($sk(35823)); $o['sk_35824']=$skz($sk(35824));
    wp_cache_flush(); $x=wc_get_order($id); $o['meta_vp']=array('siuntos'=>$x->get_meta('_ps_siuntos'),'vp_data'=>$x->get_meta('venipak_shipping_order_data'),'pak'=>$x->get_meta(Petshop_Desk::META_PAK)); $o['pastabos']=array_map(function($n){return mb_substr($n->content,0,160);},wc_get_order_notes(array('order_id'=>$id,'limit'=>5)));
    $o['sargas']=$wpdb->get_results("SELECT laikas,lygis,LEFT(zinute,200) z,failas,eilute FROM {$p}ps_sargas_klaidos ORDER BY id DESC LIMIT 5",ARRAY_A);
    $r=$G(admin_url('admin.php?page=ps-desk&eile=laiskai'),120); $h=(string)wp_remote_retrieve_body($r); $o['vf_zingsniai']=preg_match('/<div class="dl-zingsniai-k">(.*?)<form/su',substr($h,(int)strpos($h,'Užsakyti iš VF')),$m)?mb_substr(strip_tags($m[1],'<a><button><span>'),0,700):'NĖRA'; $o['vf_eil']=preg_match_all('/data-lip="(\d)"/',$h,$ml)?$ml[1]:array(); $o['be_lipduko_tekstai']=preg_match_all('/<span class="kel[^"]*"><i><\/i>([^<]+)<\/span>/u',$h,$mt)?array_slice($mt[1],0,6):array();
    $J($o); }
  if($f==='K'){ $ids=(array)get_option('ps_e17_ids',array()); $ck=array(); foreach($cs as $c){ $ck[]=array('name'=>$c->name,'value'=>$c->value); }
    $o['cookies']=$ck; $o['shots']=array(array('n'=>'s1625_e17_skydelis_vidine','u'=>admin_url('admin.php?page=ps-desk&eile=visi'),'w'=>1440,'h'=>1000,'click'=>'tr.eil[data-id="35821"] td','eval'=>"(async()=>{ for(var i=0;i<20;i++){ if(document.getElementById('skVidT')) break; await new Promise(r=>setTimeout(r,500)); } await new Promise(r=>setTimeout(r,500)); return !!document.getElementById('skVidT'); })()"),array('n'=>'s1625_e17_dropshipping','u'=>admin_url('admin.php?page=ps-desk&eile=laiskai'),'w'=>1440,'h'=>900)); $J($o); }
  }catch(Throwable $e){ $o['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $J($o);
},99);
