<?php
/** TEMP PS S1637 run j — juostos/sticky diagnostika (READ-ONLY): katalogo puslapio matavimai per testuotoja. */
add_action('init', function(){
  if (!isset($_GET['ps_s1637j'])) return;
  $o=array('v'=>'S1637 j'); global $wpdb; $p=$wpdb->prefix;
  $o['temp_istrinta']=(int)$wpdb->query("DELETE FROM {$p}snippets WHERE name LIKE 'TEMP%' AND active=0");
  $tu=get_user_by('login','testuotojas'); $uid=$tu->ID; $exp=time()+1200; $tok=WP_Session_Tokens::get_instance($uid)->create($exp);
  $o['cookies']=array(
    array('name'=>SECURE_AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'secure_auth',$tok)),
    array('name'=>AUTH_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'auth',$tok)),
    array('name'=>LOGGED_IN_COOKIE,'value'=>wp_generate_auth_cookie($uid,$exp,'logged_in',$tok)));
  $u=admin_url('admin.php?page=ps-katalogas&kruva=prekyboje&view=visos_kruvoje&q=tofu');
  $sh=json_decode('[{"n": "s1637_j_1366", "u": "", "w": 1366, "h": 768, "eval": "(async()=>{ window.scrollTo(300,600); await new Promise(r=>setTimeout(r,600));\n var cs=getComputedStyle(document.documentElement).getPropertyValue(\'--ps-virsus\');\n var b=document.querySelector(\'.pskat-bar\'); var th=document.querySelector(\'.pskat-lent-lauk .pskat-t thead th\');\n var lauk=document.querySelector(\'.pskat-lent-lauk\'); var lcs=lauk?getComputedStyle(lauk):null;\n return {virsus:cs, scrollY:window.scrollY, scrollX:window.scrollX,\n  bar: b?{top:Math.round(b.getBoundingClientRect().top),bottom:Math.round(b.getBoundingClientRect().bottom),pos:getComputedStyle(b).position}:null,\n  thead: th?{top:Math.round(th.getBoundingClientRect().top),pos:getComputedStyle(th).position,cssTop:getComputedStyle(th).top}:null,\n  lauk: lauk?{ovx:lcs.overflowX,ovy:lcs.overflowY,scrollH:lauk.scrollHeight,clientH:lauk.clientHeight,rectTop:Math.round(lauk.getBoundingClientRect().top)}:null,\n  docScroll: document.scrollingElement===document.documentElement?\'html\':\'kitas\',\n  wpwrapOv: getComputedStyle(document.getElementById(\'wpbody-content\')||document.body).overflow};})()"}, {"n": "s1637_j_1280", "u": "", "w": 1280, "h": 768, "eval": "(async()=>{ window.scrollTo(300,600); await new Promise(r=>setTimeout(r,600));\n var cs=getComputedStyle(document.documentElement).getPropertyValue(\'--ps-virsus\');\n var b=document.querySelector(\'.pskat-bar\'); var th=document.querySelector(\'.pskat-lent-lauk .pskat-t thead th\');\n var lauk=document.querySelector(\'.pskat-lent-lauk\'); var lcs=lauk?getComputedStyle(lauk):null;\n return {virsus:cs, scrollY:window.scrollY, scrollX:window.scrollX,\n  bar: b?{top:Math.round(b.getBoundingClientRect().top),bottom:Math.round(b.getBoundingClientRect().bottom),pos:getComputedStyle(b).position}:null,\n  thead: th?{top:Math.round(th.getBoundingClientRect().top),pos:getComputedStyle(th).position,cssTop:getComputedStyle(th).top}:null,\n  lauk: lauk?{ovx:lcs.overflowX,ovy:lcs.overflowY,scrollH:lauk.scrollHeight,clientH:lauk.clientHeight,rectTop:Math.round(lauk.getBoundingClientRect().top)}:null,\n  docScroll: document.scrollingElement===document.documentElement?\'html\':\'kitas\',\n  wpwrapOv: getComputedStyle(document.getElementById(\'wpbody-content\')||document.body).overflow};})()"}]',true); foreach($sh as &$s){ $s['u']=$u; } unset($s);
  $o['shots']=$sh;
  header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE); exit;
},99);
