<?php
/** TEMP PS S1678 k3 — READ-ONLY: vienkartiniai vs grįžtantys pagal pirmą kanalą, ką pirko vienkartiniai, pirmo užsakymo AOV. */
add_action('init', function(){
  if (!isset($_GET['ps_sec8k3'])) return; global $wpdb; $p=$wpdb->prefix; $o=array('v'=>'S1678 k3'); $wpdb->suppress_errors(true);
  $U="{$p}ps_ist_fakt_uzsakymai"; $E="{$p}ps_ist_fakt_eilutes";
  $o['kanalai']=$wpdb->get_results("SELECT COALESCE(NULLIF(kanalas_pirmas,''),'(nėra)') k, COUNT(*) n FROM $U WHERE apmoketa_at>DATE_SUB(NOW(),INTERVAL 24 MONTH) GROUP BY k ORDER BY n DESC LIMIT 10",ARRAY_A);
  // klientai, kurių pirmas užsakymas 12–24 mėn. atgal (turėjo 12 mėn. grįžti): ar grįžo, pagal pirmo užsakymo kanalą
  $o['grizo_pagal_kanala']=$wpdb->get_results("SELECT COALESCE(NULLIF(f.kanalas_pirmas,''),'(nėra)') k, COUNT(*) klientai, SUM(t.n>1) grizo, ROUND(SUM(t.n>1)/COUNT(*)*100) pct, ROUND(AVG(f.viso_ct)/100,1) pirmo_aov FROM (SELECT klientas_id, MIN(apmoketa_at) pirma, COUNT(*) n FROM $U GROUP BY klientas_id HAVING pirma BETWEEN DATE_SUB(NOW(),INTERVAL 24 MONTH) AND DATE_SUB(NOW(),INTERVAL 12 MONTH)) t JOIN $U f ON f.klientas_id=t.klientas_id AND f.apmoketa_at=t.pirma GROUP BY k ORDER BY klientai DESC LIMIT 10",ARRAY_A);
  $o['grizo_pagal_gclid']=$wpdb->get_results("SELECT (f.gclid<>'' AND f.gclid IS NOT NULL) ads, COUNT(*) klientai, SUM(t.n>1) grizo, ROUND(SUM(t.n>1)/COUNT(*)*100) pct, ROUND(AVG(f.viso_ct)/100,1) pirmo_aov FROM (SELECT klientas_id, MIN(apmoketa_at) pirma, COUNT(*) n FROM $U GROUP BY klientas_id HAVING pirma BETWEEN DATE_SUB(NOW(),INTERVAL 24 MONTH) AND DATE_SUB(NOW(),INTERVAL 12 MONTH)) t JOIN $U f ON f.klientas_id=t.klientas_id AND f.apmoketa_at=t.pirma GROUP BY ads",ARRAY_A);
  $o['grizo_pagal_brenda']=$wpdb->get_results("SELECT e.brendas_slug b, COUNT(DISTINCT t.klientas_id) klientai, COUNT(DISTINCT CASE WHEN t.n>1 THEN t.klientas_id END) grizo, ROUND(COUNT(DISTINCT CASE WHEN t.n>1 THEN t.klientas_id END)/COUNT(DISTINCT t.klientas_id)*100) pct FROM (SELECT klientas_id, MIN(apmoketa_at) pirma, COUNT(*) n FROM $U GROUP BY klientas_id HAVING pirma BETWEEN DATE_SUB(NOW(),INTERVAL 24 MONTH) AND DATE_SUB(NOW(),INTERVAL 12 MONTH)) t JOIN $U f ON f.klientas_id=t.klientas_id AND f.apmoketa_at=t.pirma JOIN $E e ON e.uzsakymas_id=f.uzsakymas_id GROUP BY b HAVING klientai>=25 ORDER BY klientai DESC LIMIT 15",ARRAY_A);
  $o['grizo_pagal_aov']=$wpdb->get_results("SELECT CASE WHEN f.viso_ct<2000 THEN '<20' WHEN f.viso_ct<3500 THEN '20-35' WHEN f.viso_ct<6000 THEN '35-60' ELSE '60+' END b, COUNT(*) klientai, ROUND(SUM(t.n>1)/COUNT(*)*100) pct FROM (SELECT klientas_id, MIN(apmoketa_at) pirma, COUNT(*) n FROM $U GROUP BY klientas_id HAVING pirma BETWEEN DATE_SUB(NOW(),INTERVAL 24 MONTH) AND DATE_SUB(NOW(),INTERVAL 12 MONTH)) t JOIN $U f ON f.klientas_id=t.klientas_id AND f.apmoketa_at=t.pirma GROUP BY b ORDER BY MIN(f.viso_ct)",ARRAY_A);
  header('Content-Type: application/json'); echo json_encode($o,JSON_UNESCAPED_UNICODE); exit;
});
