<?php
/** TEMP PS S1683t s — read-only: prekė 18054 pilnai (statusas, kainos, sku, likutis, istorija, kaip matoma), #1060 užsakymas, 18054 pardavimai istorijoje. */
add_action('init', function(){
  if (!isset($_GET['ps_s1683ts'])) return; global $wpdb; $p=$wpdb->prefix; $o=array('v'=>'s'); $pr=wc_get_product(18054);
  $o['preke']=array('n'=>$pr->get_name(),'status'=>$pr->get_status(),'vis'=>$pr->get_catalog_visibility(),'sku'=>$pr->get_sku(),'reg'=>$pr->get_regular_price(),'sale'=>$pr->get_sale_price(),'price'=>$pr->get_price(),'stock'=>$pr->get_stock_quantity(),'mng'=>$pr->get_manage_stock(),'st'=>$pr->get_stock_status(),'svoris'=>$pr->get_weight(),'kat'=>implode('|',wp_get_post_terms(18054,'product_cat',array('fields'=>'names'))),'mod'=>$pr->get_date_modified()->date('Y-m-d H:i'),'url'=>get_permalink(18054));
  $m=array(); foreach($pr->get_meta_data() as $md) if(!preg_match('/_ps_ga|_yoast|_elementor|desc|_wp_/i',$md->key)) $m[$md->key]=substr(json_encode($md->value,JSON_UNESCAPED_UNICODE),0,60); $o['meta']=$m;
  $o['revs']=$wpdb->get_results("SELECT post_date,LEFT(post_excerpt,60) e FROM {$p}posts WHERE post_parent=18054 AND post_type='revision' ORDER BY post_date DESC LIMIT 3",ARRAY_A);
  $o['ist']=$wpdb->get_results("SELECT COUNT(*) n,MAX(e.kaina_ct) max_ct,MIN(e.kaina_ct) min_ct FROM {$p}ps_ist_fakt_eilutes e WHERE e.product_id=18054",ARRAY_A); if($wpdb->last_error){ $o['ist_e']=$wpdb->last_error; $o['ist_cols']=$wpdb->get_col("SHOW COLUMNS FROM {$p}ps_ist_fakt_eilutes"); }
  $w=wc_get_order(35958); $o['uzs']=array('nr'=>$w->get_order_number(),'st'=>$w->get_status(),'apm'=>$w->get_payment_method(),'viso'=>$w->get_total(),'siunt'=>$w->get_shipping_total(),'sm'=>implode('|',array_map(function($s){return $s->get_name();},$w->get_shipping_methods())),'klientas'=>$w->get_billing_first_name().' '.$w->get_billing_last_name(),'items'=>array_map(function($i){return $i->get_name().' x'.$i->get_quantity().' '.$i->get_total();},array_values($w->get_items())),'src'=>$w->get_meta('_wc_order_attribution_utm_source').'/'.$w->get_meta('_wc_order_attribution_source_type'),'pastabos'=>array_map(function($n){return substr($n->content,0,120);},array_slice(wc_get_order_notes(array('order_id'=>35958,'limit'=>6)),0,6)));
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($o,JSON_UNESCAPED_UNICODE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit;
});
