<?php
/** Plugin Name: TEMP PS S1719b — audito tęsinys, read-only (e failai/HTTP/konfig, f WC vientisumas, g žurnalai/sesijos/DB) */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1719b'])) return; $f=$_GET['ps_s1719b']; $r=['v'=>'S1719b','faze'=>$f,'t'=>date('Y-m-d H:i:s'),'host'=>$_SERVER['HTTP_HOST']??null,'sw'=>$_SERVER['SERVER_SOFTWARE']??null];
  global $wpdb; $p=$wpdb->prefix; @set_time_limit(280); @ini_set('memory_limit','512M');
  $q=function($sql) use($wpdb){ $wpdb->last_error=''; $x=$wpdb->get_results($sql,ARRAY_A); if($wpdb->last_error) return ['SQL_ERR'=>substr($wpdb->last_error,0,160)]; return $x; };
  $mask=function($s){ return preg_replace(['/(PASS|SECRET|TOKEN|KEY|RAKT|slapt)([^\n]{0,20}?[\'"=:,>\s]+)[^\'"\s]{4,}/i','/gh[pousr]_[A-Za-z0-9]{10,}/','/github_pat_[A-Za-z0-9_]{10,}/'],['$1$2***','ghp_***','github_pat_***'],$s); };
  $head=function($fp,$n=40) use($mask){ if(!file_exists($fp)) return null; $l=array_slice(file($fp),0,$n); return array_map(function($x) use($mask){ return $mask(rtrim(substr($x,0,160))); },$l); };
  $home=dirname(dirname(dirname(ABSPATH))); $dom=dirname(ABSPATH); $T0=microtime(true);
  try{
  if($f==='e'){
    $r['home']=$home; $r['open_basedir']=ini_get('open_basedir');
    $dev='/home/gyvunai2/domains/avesa.lt/public_html/dev/index.php'; $r['dev_index']=file_exists($dev)?substr($mask(file_get_contents($dev)),0,300):'(nėra)';
    $r['dev_dir']=is_dir(dirname($dev))?array_map('basename',glob(dirname($dev).'/*')):null; $r['avesa_public']=is_dir('/home/gyvunai2/domains/avesa.lt/public_html')?array_slice(array_map('basename',glob('/home/gyvunai2/domains/avesa.lt/public_html/*')),0,20):null;
    $r['dns_dev']=gethostbyname('dev.avesa.lt'); $r['dns_petshop']=gethostbyname('petshop.lt');
    $urls=['https://dev.avesa.lt/','https://dev.avesa.lt/wp-login.php','https://dev.avesa.lt/wp-content/uploads/petshop-vf-cache.xml','https://dev.avesa.lt/kategorija/sunims/','https://avesa.lt/','https://petshop.lt/wp-content/phptest.php','https://petshop.lt/wp-content/petshop-xml-vf-fetcher.php','https://petshop.lt/wp-content/ps_private/','https://petshop.lt/wp-content/petshop-private-logs/','https://petshop.lt/watch-run.php','https://petshop.lt/wp-content/uploads/vetfarmas_response_20260602_142756.xml','https://petshop.lt/wp-content/uploads/cmp_result.json','https://petshop.lt/wp-content/uploads/ps-backups/google.xml.bak_s1671','https://petshop.lt/wp-content/uploads/ps-backups/snippet-567.bak_s1676.php','https://petshop.lt/wp-content/mu-plugins/ps-backup/','https://petshop.lt/wp-content/uploads/wc-logs/index.html','https://petshop.lt/wp-content/wp-cache-config.php','https://petshop.lt/wp-content/uploads/ps-backups/wp-config.php.bak_s1675','https://petshop.lt/index.html.backup.5a6defd0b6c8b4cd418a970086e2c0b4','https://petshop.lt/wp-content/plugins/petshop-xml/','https://petshop.lt/wp-content/upgrade-temp-backup/','https://petshop.lt/wp-content/ps-backups/','https://www.petshop.lt/','http://petshop.lt/'];
    $lp=glob(wp_upload_dir()['basedir'].'/ps-lipdukai/lp/*.pdf'); if($lp){ $r['lp_pdf_pvz']=basename($lp[0]); $urls[]='https://petshop.lt/wp-content/uploads/ps-lipdukai/lp/'.basename($lp[0]); }
    $vp=glob(wp_upload_dir()['basedir'].'/ps-lipdukai/*/*.pdf'); $r['lipduku_pdf_n']=count($vp?:[]); $r['lipduku_dirs']=array_map('basename',glob(wp_upload_dir()['basedir'].'/ps-lipdukai/*'));
    if($vp){ foreach($vp as $x){ if(strpos($x,'/lp/')===false){ $r['vp_pdf_pvz']=str_replace(wp_upload_dir()['basedir'],'',$x); $urls[]='https://petshop.lt/wp-content/uploads'.$r['vp_pdf_pvz']; break; } } }
    foreach($urls as $u){ $rs=wp_remote_get($u,['timeout'=>12,'redirection'=>0,'user-agent'=>'Mozilla/5.0 (Windows NT 10.0) ps-audit','sslverify'=>false,'limit_response_size'=>3000]); if(is_wp_error($rs)){ $r['http'][$u]='ERR '.substr($rs->get_error_message(),0,70); continue;} $c=wp_remote_retrieve_response_code($rs); $b=(string)wp_remote_retrieve_body($rs); $ct=wp_remote_retrieve_header($rs,'content-type'); $loc=wp_remote_retrieve_header($rs,'location'); $cl=wp_remote_retrieve_header($rs,'content-length'); preg_match('/<link rel="canonical" href="([^"]+)"/',$b,$cm); $r['http'][$u]=$c.' '.substr((string)$ct,0,20).($cl?' '.$cl.'B':'').($loc?' → '.substr($loc,0,70):'').($cm?' canon:'.substr($cm[1],0,50):'').(($c==200&&preg_match('#Index of#i',$b))?' LISTING!':'').(($c==200&&!preg_match('#text/html#',(string)$ct))?' body:'.substr(preg_replace('/\s+/',' ',strip_tags($b)),0,60):'').(($c==200&&preg_match('#phptest|fetcher|watch-run|backup#',$u))?' body:'.substr(preg_replace('/\s+/',' ',strip_tags($b)),0,80):''); }
    foreach(['wp-content/phptest.php','wp-content/petshop-xml-vf-fetcher.php','backup-run.php','watch-run.php'] as $x){ $r['failas'][$x]=['bytes'=>@filesize(ABSPATH.$x),'mtime'=>file_exists(ABSPATH.$x)?date('Y-m-d',filemtime(ABSPATH.$x)):null,'head'=>$head(ABSPATH.$x,22)]; }
    $r['htaccess_root']=array_values(array_filter(array_map('trim',file(ABSPATH.'.htaccess')),function($l){return $l!=='';}));
    foreach(['wp-content/ps_private','wp-content/petshop-private-logs','wp-content/mu-plugins/ps-backup','wp-content/ps-backups','wp-content/upgrade-temp-backup','wp-content/upgrade'] as $d){ $fs=glob(ABSPATH.$d.'/*')?:[]; usort($fs,function($a,$b){return filemtime($b)-filemtime($a);}); $r['dir'][$d]=['n'=>count($fs),'ht'=>file_exists(ABSPATH.$d.'/.htaccess'),'naujausi'=>array_map(function($x){return [basename($x),is_dir($x)?'dir':round(filesize($x)/1024).'kb',date('m-d',filemtime($x))];},array_slice($fs,0,8))]; }
    $bk=glob(ABSPATH.'wp-content/mu-plugins/ps-backup/*.php'); if($bk) $r['ps_backup_head']=$head($bk[0],30);
    $r['ps_backup_opcijos']=$q("SELECT option_name,LEFT(REPLACE(option_value,'\"',''),200) v FROM {$p}options WHERE option_name LIKE 'ps_backup%' OR option_name LIKE 'ps_atsargin%' OR option_name LIKE '%backup_last%' LIMIT 15");
    foreach([$home.'/backups',$home.'/.appdata',$home.'/admin_backups',$home.'/user_backups',$dom.'/backups',$dom.'/ps-archyvas',$dom.'/logs',$dom.'/private_html',$home] as $d){ $fs=@glob($d.'/*')?:[]; if(!$fs&&!is_dir($d)){ $r['bk_dirs'][$d]=null; continue; } usort($fs,function($a,$b){return filemtime($b)-filemtime($a);}); $r['bk_dirs'][$d]=['n'=>count($fs),'naujausi'=>array_map(function($x){return [basename($x),is_dir($x)?'dir':round(filesize($x)/1048576,1).'MB',date('m-d H:i',filemtime($x))];},array_slice($fs,0,10))]; }
    $found=[]; $t0=microtime(true); try{ $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($home,FilesystemIterator::SKIP_DOTS|FilesystemIterator::FOLLOW_SYMLINKS),RecursiveIteratorIterator::SELF_FIRST); $it->setMaxDepth(3); $n=0; foreach($it as $fi){ $n++; if($n>40000||microtime(true)-$t0>40) break; if($fi->isFile()&&preg_match('/\.(tar\.gz|tgz|zip|sql|sql\.gz|7z)$/i',$fi->getFilename())&&$fi->getMTime()>time()-45*86400) $found[]=[str_replace($home,'~',$fi->getPathname()),round($fi->getSize()/1048576,1).'MB',date('m-d',$fi->getMTime())]; } }catch(Throwable $e){ $r['bk_scan_err']=$e->getMessage(); }
    $r['bk_failai_45d']=array_slice($found,0,20);
    $up=wp_upload_dir()['basedir']; $php=[]; try{ $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($up,FilesystemIterator::SKIP_DOTS)); foreach($it as $fi){ if($fi->isFile()&&preg_match('/\.(php|phtml|php[0-9]|phar)$/i',$fi->getFilename())&&$fi->getFilename()!=='index.php') $php[]=[str_replace($up,'',$fi->getPathname()),round($fi->getSize()/1024).'kb',date('m-d',$fi->getMTime())]; } }catch(Throwable $e){} $r['uploads_php_ne_index']=array_slice($php,0,40);
    $r['uploads_root']=array_map(function($x){return [basename($x),is_dir($x)?'dir':round(filesize($x)/1024).'kb',date('m-d',filemtime($x))];},glob($up.'/*'));
    $r['opcache_ini']=['memory'=>ini_get('opcache.memory_consumption'),'max_files'=>ini_get('opcache.max_accelerated_files'),'validate'=>ini_get('opcache.validate_timestamps'),'revalidate'=>ini_get('opcache.revalidate_freq'),'interned'=>ini_get('opcache.interned_strings_buffer'),'jit'=>ini_get('opcache.jit'),'jit_buf'=>ini_get('opcache.jit_buffer_size'),'enable_cli'=>ini_get('opcache.enable_cli'),'php_ini'=>php_ini_loaded_file(),'scanned'=>php_ini_scanned_files(),'user_ini'=>file_exists(ABSPATH.'.user.ini')?$head(ABSPATH.'.user.ini',20):null,'php_ini_root'=>file_exists(ABSPATH.'php.ini')?$head(ABSPATH.'php.ini',20):null,'pid'=>getmypid()];
    $oc=@opcache_get_status(false); if($oc) $r['opcache_now']=['full'=>$oc['cache_full'],'start'=>date('m-d H:i',$oc['opcache_statistics']['start_time']),'last_restart'=>$oc['opcache_statistics']['last_restart_time']?date('m-d H:i',$oc['opcache_statistics']['last_restart_time']):null,'hits'=>$oc['opcache_statistics']['hits'],'misses'=>$oc['opcache_statistics']['misses'],'scripts'=>$oc['opcache_statistics']['num_cached_scripts']];
    try{ if(class_exists('Memcached')){ $m=new Memcached(); $m->addServer('127.0.0.1',11211); $v=$m->getVersion(); $r['memcached_local']=$v?:'nėra'; } else $r['memcached_local']='klasės nėra'; }catch(Throwable $e){ $r['memcached_local']='klaida '.$e->getMessage(); }
    $r['mysql']=$q("SHOW GLOBAL VARIABLES WHERE Variable_name IN ('innodb_buffer_pool_size','max_connections','query_cache_type','tmp_table_size','max_allowed_packet','innodb_flush_log_at_trx_commit','version')");
    $r['mysql_status']=$q("SHOW GLOBAL STATUS WHERE Variable_name IN ('Uptime','Threads_connected','Threads_running','Slow_queries','Questions','Created_tmp_disk_tables','Innodb_buffer_pool_reads','Innodb_buffer_pool_read_requests','Aborted_connects','Max_used_connections')");
    $role=get_role('ps_darbuotojas'); $r['ps_darbuotojas_caps']=$role?array_keys(array_filter($role->capabilities)):null;
    $ap=WP_Application_Passwords::get_user_application_passwords(1); $r['app_pw_admin']=array_map(function($x){return ['name'=>$x['name'],'created'=>date('Y-m-d',$x['created']),'last_used'=>$x['last_used']?date('Y-m-d H:i',$x['last_used']):null,'last_ip'=>$x['last_ip']??null];},$ap);
    $r['auto_update_list']=['plugins'=>get_option('auto_update_plugins'),'themes'=>get_option('auto_update_themes')];
    $r['env_type']=wp_get_environment_type(); $r['home_siteurl']=[get_option('home'),get_option('siteurl')];
    global $cache_rejected_uri,$wp_cache_pages,$wp_super_cache_late_init,$wp_cache_mutex_disabled,$cache_acceptable_files,$wp_cache_no_cache_for_get; $r['supercache_extra']=['rejected_uri'=>$cache_rejected_uri,'pages'=>$wp_cache_pages,'late_init'=>$wp_super_cache_late_init,'no_cache_get'=>$wp_cache_no_cache_for_get];
    $snip=$q("SELECT id,name,LENGTH(code) len,(code REGEXP 'gh[pousr]_[A-Za-z0-9]{20,}|github_pat_|Bearer [A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,}') tok FROM {$p}snippets WHERE active=1 ORDER BY id"); $r['snippets_active']=array_map(function($x){return $x['id'].' '.$x['name'].' ('.round($x['len']/1024).'k'.($x['tok']?' TOKENAS!':'').')';},$snip?:[]);
    foreach([469,465] as $sid){ $c=$wpdb->get_var($wpdb->prepare("SELECT code FROM {$p}snippets WHERE id=%d",$sid)); $r['snippet_'.$sid]=$c?substr($mask($c),0,900):null; }
    $r['snippets_inactive_temp']=$q("SELECT COUNT(*) n,ROUND(SUM(LENGTH(code))/1024/1024,1) mb FROM {$p}snippets WHERE active=0 AND name LIKE 'TEMP%'");
    $r['logs_dir']=array_map(function($x){return [basename($x),round(filesize($x)/1048576,1).'MB',date('m-d H:i',filemtime($x))];},glob($dom.'/logs/*')?:[]);
  }
  if($f==='f'){
    $r['processing_be_siuntos_3d']=$q("SELECT o.id,od.date_paid_gmt,o.total_amount,o.payment_method FROM {$p}wc_orders o JOIN {$p}wc_order_operational_data od ON od.order_id=o.id WHERE o.type='shop_order' AND o.status='wc-processing' AND od.date_paid_gmt<UTC_TIMESTAMP()-INTERVAL 3 DAY AND NOT EXISTS(SELECT 1 FROM {$p}ps_fakt_siuntos s WHERE s.uzsakymas_id=o.id) ORDER BY o.id LIMIT 15");
    $r['processing_visi']=$q("SELECT o.id,od.date_paid_gmt,o.total_amount,(SELECT COUNT(*) FROM {$p}ps_fakt_siuntos s WHERE s.uzsakymas_id=o.id) siuntos FROM {$p}wc_orders o LEFT JOIN {$p}wc_order_operational_data od ON od.order_id=o.id WHERE o.type='shop_order' AND o.status='wc-processing' ORDER BY o.id");
    $r['onhold']=$q("SELECT o.id,o.date_created_gmt,o.payment_method,o.total_amount FROM {$p}wc_orders o WHERE o.type='shop_order' AND o.status='wc-on-hold'");
    $r['apmoketi_eilutes_be_zymiu']=$q("SELECT o.id,COUNT(*) eil FROM {$p}wc_orders o JOIN {$p}wc_order_operational_data od ON od.order_id=o.id JOIN {$p}woocommerce_order_items i ON i.order_id=o.id AND i.order_item_type='line_item' WHERE o.type='shop_order' AND o.status IN ('wc-processing','wc-completed') AND od.date_paid_gmt>='2026-09-09' AND NOT EXISTS(SELECT 1 FROM {$p}woocommerce_order_itemmeta im WHERE im.order_item_id=i.order_item_id AND im.meta_key IN ('_reduced_stock','_ps_av_reduced_qty','_ps_av_reduced','_ps_source','_mnm_container')) GROUP BY o.id ORDER BY o.id DESC LIMIT 20");
    $r['apmoketi_be_kelio']=$q("SELECT o.id,COUNT(*) eil FROM {$p}wc_orders o JOIN {$p}wc_order_operational_data od ON od.order_id=o.id JOIN {$p}woocommerce_order_items i ON i.order_id=o.id AND i.order_item_type='line_item' WHERE o.type='shop_order' AND o.status IN ('wc-processing','wc-completed') AND od.date_paid_gmt>='2026-09-09' AND NOT EXISTS(SELECT 1 FROM {$p}woocommerce_order_itemmeta im WHERE im.order_item_id=i.order_item_id AND im.meta_key IN ('_ps_source','_mnm_config','_mnm_container')) GROUP BY o.id ORDER BY o.id DESC LIMIT 20");
    foreach([35902,36102,36143,36145,36250] as $oid){ $o=wc_get_order($oid); if(!$o){ $r['atsaukti'][$oid]='nėra'; continue; } $ls=[]; foreach($o->get_items() as $it){ $ls[]=[$it->get_product_id(),substr($it->get_name(),0,30),'q'=>$it->get_quantity(),'rs'=>$it->get_meta('_reduced_stock'),'avq'=>$it->get_meta('_ps_av_reduced_qty'),'avr'=>$it->get_meta('_ps_av_reduced'),'avrest'=>$it->get_meta('_ps_av_restored'),'src'=>$it->get_meta('_ps_source')]; }
      $notes=array_slice(array_map(function($n){return substr($n->date_created->date('m-d H:i').' '.strip_tags($n->content),0,110);},array_filter(wc_get_order_notes(['order_id'=>$oid]),function($n){return preg_match('/likut|grąž|graz|atšauk|atsauk|nuraš|nuras/iu',$n->content);})),0,5);
      $r['atsaukti'][$oid]=['nr'=>$o->get_order_number(),'st'=>$o->get_status(),'pm'=>$o->get_payment_method(),'paid'=>(bool)$o->get_date_paid(),'stock_reduced'=>$o->get_data_store()->get_stock_reduced($oid),'av_restored'=>$o->get_meta('_ps_av_restored'),'av_reduced'=>$o->get_meta('_ps_av_reduced'),'eil'=>$ls,'notes'=>$notes]; }
    $av=$wpdb->get_col("SELECT meta_value FROM {$p}wc_orders_meta WHERE meta_key='_petshop_avpn_number' ORDER BY meta_value"); $nums=[]; foreach($av as $v){ if(preg_match('/(\d+)$/',$v,$m)) $nums[]=(int)$m[1]; } sort($nums); $gaps=[]; $dupl=[]; for($i=1;$i<count($nums);$i++){ if($nums[$i]==$nums[$i-1]) $dupl[]=$nums[$i]; elseif($nums[$i]-$nums[$i-1]>1) for($g=$nums[$i-1]+1;$g<$nums[$i];$g++) $gaps[]=$g; } $r['avpn']=['n'=>count($nums),'min'=>$nums?min($nums):null,'max'=>$nums?max($nums):null,'counter'=>get_option('petshop_avpn_counter'),'spragos'=>array_slice($gaps,0,40),'spragu_n'=>count($gaps),'dubl'=>$dupl,'pvz'=>array_slice($av,0,3)];
    $r['avpn_pagal_statusa']=$q("SELECT o.status,COUNT(*) n FROM {$p}wc_orders_meta m JOIN {$p}wc_orders o ON o.id=m.order_id WHERE m.meta_key='_petshop_avpn_number' GROUP BY o.status");
    $r['wcdn_avpn_pvz']=$q("SELECT order_id,meta_value FROM {$p}wc_orders_meta WHERE meta_key='_wcdn_invoice_number' ORDER BY order_id DESC LIMIT 5");
    $r['doc_type']=$q("SELECT meta_value,COUNT(*) n FROM {$p}wc_orders_meta WHERE meta_key='_petshop_invoice_document_type' GROUP BY meta_value");
    $r['sources_av_vs_own_top']=$q("SELECT s.product_id,LEFT(p.post_title,40) t,s.stock_qty src_qty,o.meta_value own,st.meta_value stock,sd.meta_value sandelis,p.post_status FROM {$p}ps_sources s JOIN {$p}posts p ON p.ID=s.product_id LEFT JOIN {$p}postmeta o ON o.post_id=s.product_id AND o.meta_key='_own_stock_qty' LEFT JOIN {$p}postmeta st ON st.post_id=s.product_id AND st.meta_key='_stock' LEFT JOIN {$p}postmeta sd ON sd.post_id=s.product_id AND sd.meta_key='_ps_sandelis' WHERE s.source='av' AND s.is_active=1 AND s.stock_qty<>COALESCE(o.meta_value+0,st.meta_value+0,0) ORDER BY ABS(s.stock_qty-COALESCE(o.meta_value+0,st.meta_value+0,0)) DESC LIMIT 15");
    $r['sources_av_vs_own_tipai']=$q("SELECT p.post_type,p.post_status,COUNT(*) n FROM {$p}ps_sources s JOIN {$p}posts p ON p.ID=s.product_id LEFT JOIN {$p}postmeta o ON o.post_id=s.product_id AND o.meta_key='_own_stock_qty' LEFT JOIN {$p}postmeta st ON st.post_id=s.product_id AND st.meta_key='_stock' WHERE s.source='av' AND s.is_active=1 AND s.stock_qty<>COALESCE(o.meta_value+0,st.meta_value+0,0) GROUP BY p.post_type,p.post_status");
    $r['partijos_vs_av']=$q("SELECT COUNT(*) n, SUM(x.part<>x.av) nesutampa, SUM(x.part) part_sum, SUM(x.av) av_sum FROM (SELECT pa.product_id, SUM(pa.kiekis_liko) part, COALESCE(MAX(o.meta_value+0),MAX(st.meta_value+0),0) av FROM {$p}ps_partijos pa LEFT JOIN {$p}postmeta o ON o.post_id=pa.product_id AND o.meta_key='_own_stock_qty' LEFT JOIN {$p}postmeta st ON st.post_id=pa.product_id AND st.meta_key='_stock' WHERE pa.atsaukta=0 GROUP BY pa.product_id) x");
    $r['partijos_vs_av_top']=$q("SELECT x.product_id,LEFT(p.post_title,40) t,x.part,x.av,sd.meta_value sandelis,p.post_status FROM (SELECT pa.product_id, SUM(pa.kiekis_liko) part, COALESCE(MAX(o.meta_value+0),MAX(st.meta_value+0),0) av FROM {$p}ps_partijos pa LEFT JOIN {$p}postmeta o ON o.post_id=pa.product_id AND o.meta_key='_own_stock_qty' LEFT JOIN {$p}postmeta st ON st.post_id=pa.product_id AND st.meta_key='_stock' WHERE pa.atsaukta=0 GROUP BY pa.product_id) x JOIN {$p}posts p ON p.ID=x.product_id LEFT JOIN {$p}postmeta sd ON sd.post_id=x.product_id AND sd.meta_key='_ps_sandelis' WHERE x.part<>x.av ORDER BY ABS(x.part-x.av) DESC LIMIT 15");
    $r['partijos_neig']=$q("SELECT COUNT(*) n FROM {$p}ps_partijos WHERE atsaukta=0 AND kiekis_liko<0");
    $r['av_be_partiju']=$q("SELECT COUNT(*) n, SUM(COALESCE(o.meta_value+0,st.meta_value+0,0)) vnt FROM {$p}posts p LEFT JOIN {$p}postmeta o ON o.post_id=p.ID AND o.meta_key='_own_stock_qty' LEFT JOIN {$p}postmeta st ON st.post_id=p.ID AND st.meta_key='_stock' LEFT JOIN {$p}postmeta sd ON sd.post_id=p.ID AND sd.meta_key='_ps_sandelis' WHERE p.post_type='product' AND p.post_status='publish' AND COALESCE(sd.meta_value,'av')='av' AND COALESCE(o.meta_value+0,st.meta_value+0,0)>0 AND NOT EXISTS(SELECT 1 FROM {$p}ps_partijos pa WHERE pa.product_id=p.ID AND pa.atsaukta=0 AND pa.kiekis_liko>0)");
    $r['be_ps_numerio_ids']=$q("SELECT o.id,o.status,o.date_created_gmt FROM {$p}wc_orders o WHERE o.type='shop_order' AND o.status<>'wc-checkout-draft' AND o.date_created_gmt>='2026-09-09' AND NOT EXISTS(SELECT 1 FROM {$p}wc_orders_meta m WHERE m.order_id=o.id AND m.meta_key='_ps_order_number')");
    $r['ean_dubl_detalės']=$q("SELECT e.meta_value ean,GROUP_CONCAT(CONCAT(p.ID,':',LEFT(p.post_title,28)) SEPARATOR ' | ') prekes FROM {$p}postmeta e JOIN {$p}posts p ON p.ID=e.post_id AND p.post_status='publish' AND p.post_type='product' WHERE e.meta_key='_ean' AND e.meta_value<>'' AND e.meta_value<>'000000000000' GROUP BY e.meta_value HAVING COUNT(*)>1 LIMIT 12");
    $r['ean_gtin_skirtingi']=$q("SELECT COUNT(*) n FROM {$p}postmeta e JOIN {$p}postmeta g ON g.post_id=e.post_id AND g.meta_key='_global_unique_id' WHERE e.meta_key='_ean' AND e.meta_value<>'' AND g.meta_value<>'' AND e.meta_value<>g.meta_value");
    $r['email_jobs_veluoja']=$q("SELECT COUNT(*) n,MIN(scheduled_at) s FROM {$p}ps_email_jobs WHERE status='pending' AND scheduled_at<UTC_TIMESTAMP()-INTERVAL 2 HOUR");
    $r['email_jobs_deferred']=$q("SELECT flow,skip_reason,block_reason,COUNT(*) n,MIN(created_at) nuo FROM {$p}ps_email_jobs WHERE status='deferred' GROUP BY flow,skip_reason,block_reason");
    $r['email_jobs_klaidos']=$q("SELECT flow,LEFT(last_error,80) e,COUNT(*) n FROM {$p}ps_email_jobs WHERE last_error<>'' AND updated_at>=UTC_TIMESTAMP()-INTERVAL 14 DAY GROUP BY flow,e LIMIT 10");
    $il=get_option('petshop_import_log'); $r['import_log_pask']=is_array($il)?array_map(function($x){ return ['kada'=>$x['kada']??null,'id'=>$x['import_id']??null,'pav'=>$x['pavadinimas']??null,'cr'=>$x['created']??null,'upd'=>$x['updated']??null,'skip'=>$x['skipped']??null,'trukme'=>$x['trukme']??null]; },array_slice($il,0,10)):$il;
    $r['import_tempas']=get_option('ps_import_tempas_paskutinis');
    $r['vf_runs']=['stock'=>get_option('petshop_vf_stock_last_run'),'reprice'=>get_option('petshop_vf_reprice_last_run'),'publish'=>get_option('petshop_vf_publish_last_run'),'feed'=>get_option('petshop_vf_feed_last_run')];
    $r['zb_opcijos']=$q("SELECT option_name,LEFT(REPLACE(option_value,'\"',''),120) v FROM {$p}options WHERE (option_name LIKE '%zb%' OR option_name LIKE '%zalioji%') AND option_name NOT LIKE '%image_index%' LIMIT 15");
    $r['vf_qty_atnaujinta']=$q("SELECT COUNT(*) n FROM {$p}postmeta WHERE meta_key='_vf_synced_at' AND meta_value>=DATE_SUB(NOW(),INTERVAL 1 DAY)");
    $r['vf_meta_raktai']=$q("SELECT meta_key,COUNT(*) n,MAX(meta_value) maxv FROM {$p}postmeta WHERE meta_key IN ('_vf_qty','_vf_synced_at','_vf_updated_at','_zb_qty','_zb_synced_at','_vf_cost','_zb_cost','_vf_last_seen','_zb_last_seen') GROUP BY meta_key");
    $r['wpai_imports']=$q("SELECT id,name,LEFT(path,60) path,registered_on,last_activity,count,processing,executing,triggered,queue_chunk_number FROM {$p}pmxi_imports ORDER BY id");
    $r['wpai_history']=$q("SELECT import_id,type,date,time_run,summary FROM {$p}pmxi_history ORDER BY id DESC LIMIT 8");
  }
  if($f==='g'){
    $r['sessions_dienos']=$q("SELECT DATE(FROM_UNIXTIME(session_expiry-172800)) d,COUNT(*) n,SUM(session_value LIKE '%\"cart\";a:0:{}%' OR session_value NOT LIKE '%\"cart\";%') tuscias,SUM(session_key REGEXP '^[0-9]+$') registruoti,ROUND(AVG(LENGTH(session_value))) vid_b FROM {$p}woocommerce_sessions GROUP BY d ORDER BY d DESC LIMIT 12");
    $r['sessions_pvz']=$q("SELECT session_key,session_expiry,LENGTH(session_value) b,LEFT(session_value,300) v FROM {$p}woocommerce_sessions WHERE session_key NOT REGEXP '^[0-9]+$' ORDER BY session_id DESC LIMIT 2");
    $r['sessions_raktai']=$q("SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(session_value,'\"',2),'\"',-1) pirmas_raktas,COUNT(*) n FROM {$p}woocommerce_sessions GROUP BY pirmas_raktas ORDER BY n DESC LIMIT 8");
    $yc=$wpdb->get_col("SHOW COLUMNS FROM {$p}yith_wcan_cache"); $r['yith_cache_cols']=$yc; $r['yith_cache']=$q("SELECT COUNT(*) n,ROUND(SUM(LENGTH(value))/1048576,1) mb,MIN(expiration) min_exp,MAX(expiration) max_exp,SUM(expiration<UNIX_TIMESTAMP()) pasibaige FROM {$p}yith_wcan_cache");
    $r['yith_cache_grupes']=$q("SELECT `group`,COUNT(*) n,ROUND(SUM(LENGTH(value))/1048576,1) mb FROM {$p}yith_wcan_cache GROUP BY `group` ORDER BY n DESC LIMIT 8");
    $r['yith_opcijos']=$q("SELECT option_name,LEFT(option_value,60) v FROM {$p}options WHERE option_name LIKE 'yith_wcan_%cache%' OR option_name LIKE 'yith_wcan_%transient%' OR option_name IN ('yith_wcan_ajax_shop_pagination','yith_wcan_lazy_load_filters')");
    $r['shortpixel']=$q("SELECT (SELECT COUNT(*) FROM {$p}shortpixel_queue) q,(SELECT COUNT(*) FROM {$p}shortpixel_postmeta) pm,(SELECT COUNT(*) FROM {$p}snippets_bak_s636) snip_bak");
    $r['carts']=$q("SELECT COUNT(*) n,MIN(created_at) nuo FROM {$p}ps_carts"); $r['ivykiai']=$q("SELECT COUNT(*) n FROM {$p}ps_ivykiai");
    $el=ini_get('error_log'); if($el&&file_exists($el)){ $sz=filesize($el); $fh=fopen($el,'r'); fseek($fh,max(0,$sz-700000)); $txt=fread($fh,700000); fclose($fh); $lines=explode("\n",$txt); $out=[];$hs=[];$stk=0;$ss=[]; foreach($lines as $i=>$ln){ if(strpos($ln,'strstr(): Argument #1')!==false&&count($out)<2){ $out[]=substr($ln,0,400); $stk=14; continue; } if($stk>0){ $ss[]=substr($ln,0,220); $stk--; } if(strpos($ln,'headers already sent')!==false&&count($hs)<2) $hs[]=substr($ln,0,400); } $r['strstr_fatal']=$out; $r['strstr_stack']=array_slice($ss,0,14); $r['headers_sent']=$hs;
      $tm=[]; foreach($lines as $ln){ if(strpos($ln,'strstr(): Argument #1')!==false&&preg_match('/^\[(\d{2}-\w{3}-\d{4} \d{2}):/',$ln,$m)) $tm[$m[1]]=($tm[$m[1]]??0)+1; } $r['strstr_val']=array_slice($tm,-20,20,true); }
    $wl=WC_LOG_DIR; foreach(glob($wl.'fatal-errors-2026-09-2*.log')?:[] as $fx){ $c=file_get_contents($fx); $pos=strpos($c,'strstr'); if($pos!==false){ $s=strrpos(substr($c,0,$pos),"\n20"); $r['wc_fatal_strstr']=substr($c,$s===false?0:$s,1800); $r['wc_fatal_strstr_n']=substr_count($c,'strstr'); $r['wc_fatal_file']=basename($fx); break; } }
    foreach(glob($wl.'fatal-errors-2026-09-24*.log')?:[] as $fx){ $c=file_get_contents($fx); preg_match_all('/CRITICAL Uncaught ([^:]{0,60}: [^\n]{0,120})/',$c,$mm); $agg=array_count_values(array_map(function($x){return preg_replace('/\d+/','#',$x);},$mm[1])); arsort($agg); $r['wc_fatal_0924_top']=array_slice($agg,0,8,true); }
    $lg=glob($dom.'/logs/*')?:[]; $acc=null; foreach($lg as $x){ if(preg_match('/petshop\.lt\.log$|access/',basename($x))&&filesize($x)>1000){ $acc=$x; break; } }
    if($acc){ $sz=filesize($acc); $fh=fopen($acc,'r'); fseek($fh,max(0,$sz-4000000)); $txt=fread($fh,4000000); fclose($fh); $ls=explode("\n",$txt); array_shift($ls); $n=0;$st=[];$ua=[];$ip=[];$cron=0;$ajax=0;$store=0;$first=null;$last=null;$paths=[];$bots=0;$fpm=[];
      foreach($ls as $ln){ if(!preg_match('/^(\S+) \S+ \S+ \[([^\]]+)\] "(\S+) (\S+)[^"]*" (\d{3}) (\S+)(?: "[^"]*" "([^"]*)")?/',$ln,$m)) continue; $n++; if(!$first) $first=$m[2]; $last=$m[2]; $st[$m[5]]=($st[$m[5]]??0)+1; $u=substr($m[7]??'-',0,60); $u=preg_replace('/^Mozilla\/5\.0 /','',$u); $ua[$u]=($ua[$u]??0)+1; $ip[$m[1]]=($ip[$m[1]]??0)+1; if(strpos($m[4],'wp-cron.php')!==false) $cron++; if(strpos($m[4],'admin-ajax.php')!==false) $ajax++; if(strpos($m[4],'wc/store')!==false||strpos($m[4],'rest_route=/wc/store')!==false) $store++; if(preg_match('/bot|crawl|spider|GPT|Claude|Bing|Yandex|Semrush|Ahrefs|python|curl|Go-http/i',$m[7]??'')) $bots++; $pth=preg_replace('/\?.*/','',$m[4]); $pth=preg_replace('/\/page\/\d+/','/page/N',$pth); $paths[$pth]=($paths[$pth]??0)+1; }
      arsort($ua); arsort($ip); arsort($paths); $r['access']=['failas'=>basename($acc),'MB'=>round($sz/1048576,1),'n'=>$n,'nuo'=>$first,'iki'=>$last,'statusai'=>$st,'botai_pct'=>$n?round(100*$bots/$n):null,'wp_cron'=>$cron,'admin_ajax'=>$ajax,'wc_store'=>$store,'ua_top'=>array_slice($ua,0,14,true),'ip_top'=>array_slice($ip,0,8,true),'keliai_top'=>array_slice($paths,0,15,true)]; }
    else $r['access']='nerasta '.json_encode(array_map('basename',$lg));
  }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $r['trukme_s']=round(microtime(true)-$T0,1); $r['mem_mb']=round(memory_get_peak_usage(true)/1048576);
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($r,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit;
},1);
