<?php
/** Plugin Name: TEMP PS S1714g filtru sargas (0 pries-testas / 1 deploy / 2 po-testas / 9 isjungti) */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1714g'])) return;
  $f=$_GET['ps_s1714g']; @set_time_limit(170); $r=['v'=>'S1714g','faze'=>$f]; $fn=WPMU_PLUGIN_DIR.'/petshop-filtru-sargas.php';
  $urls=['/kategorija/katems/?yith_wcan=1&product_cat=tualetai-kraikai-semtuveliai,kraikai-kaciu-tualetams&query_type_product_cat=or','/kategorija/katems/?yith_wcan=1&product_cat=tualetai-kraikai-semtuveliai,kraikai-kaciu-tualetams&query_type_product_cat=or&query_type_tipas=or&filter_tipas=atviras','/kategorija/katems/?product_cat=kraikai-kaciu-tualetams','/kategorija/katems/','/kategorija/sunims/maistas-sunims/sausas-maistas-sunims/?yith_wcan=1&product_cat=sausas-maistas-sunims&query_type_speciali_mityba=or&filter_speciali_mityba=hipoalerginis'];
  $test=function() use($urls){ $o=[]; foreach($urls as $u){ $h=wp_remote_get(home_url($u.'&nc='.mt_rand()),['timeout'=>60,'sslverify'=>false,'headers'=>['User-Agent'=>'Mozilla/5.0 Chrome/128']]); $b=wp_remote_retrieve_body($h); preg_match('#<h1[^>]*>(.*?)</h1>#s',$b,$m); preg_match_all('#class="product-small#',$b,$pm); $o[$u]=['kodas'=>is_wp_error($h)?'ERR':wp_remote_retrieve_response_code($h),'h1'=>trim(strip_tags($m[1]??'')),'prekiu'=>count($pm[0])]; } return $o; };
  try{
    if($f==='0'){ $r['pries']=$test(); }
    if($f==='1'){
      if(file_exists($fn)) throw new Exception('failas jau yra');
      $new=base64_decode('PD9waHAKLyoqCiAqIFBsdWdpbiBOYW1lOiBQZXRzaG9wIEZpbHRyxbMgc2FyZ2FzIHYxLjAgKDUwMCBzdSBrZWxpb21pcyBrYXRlZ29yaWpvbWlzIFlJVEggZmlsdHJlKQogKiBEZXNjcmlwdGlvbjogWUlUSCBXb29Db21tZXJjZSBBamF4IFByb2R1Y3QgRmlsdGVyIGxlaWTFvmlhIHBhxb55bcSXdGkga2VsaWFzIGthdGVnb3JpamFzIOKAlCBVUkwgZ2F1bmEKICogICBgcHJvZHVjdF9jYXQ9YSxiYCAoYXJiYSBgYStiYCkuIFdQIHXFvmtsYXVzYSB0YWkgc3VwcmFudGEsIGJldCBXb29Db21tZXJjZSBjb3JlIGZpbHRybyBteWd0dWthcwogKiAgIChXQ19XaWRnZXQ6OmdldF9jdXJyZW50X3BhZ2VfdXJsIOKGkiBnZXRfdGVybV9saW5rKCdhLGInKSkgZ2F1bmEgV1BfRXJyb3IgaXIgYWRkX3F1ZXJ5X2FyZygpIG1ldGEKICogICBUeXBlRXJyb3Ig4oaSIDUwMCB2aXNhbSBrYXRlZ29yaWpvcyBwdXNsYXBpdWkgKHBocF9lcnJvci5sb2c6IDA5LTIw4oCmMjQgcG8gN+KAkzQzL2QuKS4KICogICBTYXJnYXMgcG8gcGFncmluZGluxJdzIHXFvmtsYXVzb3MgKGB3cGAsIGthaSByZXp1bHRhdGFpIGphdSBzdXJpbmt0aSkgcGFrZWnEjWlhIGBwcm9kdWN0X2NhdGAgcXVlcnkgdmFyCiAqICAgxK8gcGlybW9zICh1xb5rbGF1c3Rvcykga2F0ZWdvcmlqb3Mgc2x1ZyfEhSDigJQgcHJla2nFsyBzxIVyYcWhbyB0YWkgbmVrZWnEjWlhLCB0aWsgbnVvcm9kxbMgZ2VuZXJhdmltxIUuCiAqIFZlcnNpb246IDEuMAogKiBTMTcxNCAoMjAyNi0wOS0yNCkuIEnFoWp1bmd0aTogb3BjaWphIGBwc19maWx0cnVfc2FyZ2FzX2lzanVuZ3RhYD0xLgogKi8KaWYgKCAhIGRlZmluZWQoICdBQlNQQVRIJyApICkgeyBleGl0OyB9CgphZGRfYWN0aW9uKCAnd3AnLCBmdW5jdGlvbiAoKSB7CglpZiAoIGdldF9vcHRpb24oICdwc19maWx0cnVfc2FyZ2FzX2lzanVuZ3RhJyApICkgeyByZXR1cm47IH0KCWlmICggISBmdW5jdGlvbl9leGlzdHMoICdpc19wcm9kdWN0X2NhdGVnb3J5JyApIHx8ICEgaXNfcHJvZHVjdF9jYXRlZ29yeSgpICkgeyByZXR1cm47IH0KCWdsb2JhbCAkd3BfcXVlcnk7CgkkdiA9IGdldF9xdWVyeV92YXIoICdwcm9kdWN0X2NhdCcgKTsKCWlmICggISBpc19zdHJpbmcoICR2ICkgfHwgISBwcmVnX21hdGNoKCAnL1ssKyBdLycsICR2ICkgKSB7IHJldHVybjsgfQoJJHEgICAgPSBnZXRfcXVlcmllZF9vYmplY3QoKTsKCSRzbHVnID0gKCAkcSAmJiAhIGVtcHR5KCAkcS0+c2x1ZyApICkgPyAkcS0+c2x1ZyA6IHByZWdfc3BsaXQoICcvWywrIF0vJywgJHYgKVswXTsKCWlmICggISAkc2x1ZyApIHsgcmV0dXJuOyB9Cgkkd3BfcXVlcnktPnF1ZXJ5X3ZhcnNbJ3Byb2R1Y3RfY2F0J10gICAgPSAkc2x1ZzsKCSR3cF9xdWVyeS0+cXVlcnlfdmFyc1sncHNfcHJvZHVjdF9jYXRfb3JpZyddID0gJHY7Cn0sIDEgKTsK'); if(md5($new)!=='458892bf509953b2a390a7e5f4cea4a6') throw new Exception('md5'); $tok=@token_get_all($new,TOKEN_PARSE); if(!$tok) throw new Exception('token');
      file_put_contents($fn,$new); $r['md5']=md5_file($fn);
      $h=wp_remote_get(home_url('/?nc='.mt_rand()),['timeout'=>40,'sslverify'=>false]); $r['heartbeat']=wp_remote_retrieve_response_code($h); if($r['heartbeat']>=500||$r['heartbeat']==0){ rename($fn,$fn.'.off_s1714'); $r['ROLLBACK']=1; }
    }
    if($f==='2'){ $r['po']=$test(); $r['php_err_tail']=array_slice(file(dirname(rtrim(ABSPATH,'/')).'/logs/php_error.log')?:[],-2); }
    if($f==='9'){ rename($fn,$fn.'.off_s1714'); $r['isjungta']=!file_exists($fn); }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.$e->getLine(); }
  wp_send_json($r);
}, 1);
