<?php
/** Plugin Name: TEMP PS S1719c — audito patikslinimai, read-only (h) */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1719c'])) return; $f=$_GET['ps_s1719c']; $r=['v'=>'S1719c','faze'=>$f,'t'=>date('Y-m-d H:i:s')];
  global $wpdb; $p=$wpdb->prefix; @set_time_limit(200);
  $q=function($sql) use($wpdb){ $wpdb->last_error=''; $x=$wpdb->get_results($sql,ARRAY_A); if($wpdb->last_error) return ['SQL_ERR'=>substr($wpdb->last_error,0,160)]; return $x; };
  $T0=microtime(true);
  try{
  if($f==='h'){
    $r['avpn_dubl']=$q("SELECT m.meta_value avpn,o.id,o.status,o.date_created_gmt,o.total_amount,(SELECT meta_value FROM {$p}wc_orders_meta x WHERE x.order_id=o.id AND x.meta_key='_ps_order_number') nr FROM {$p}wc_orders_meta m JOIN {$p}wc_orders o ON o.id=m.order_id WHERE m.meta_key='_petshop_avpn_number' AND m.meta_value IN ('AVPN011105','AVPN011134','AVPN011015','AVPN011017','AVPN011107','AVPN011109') ORDER BY m.meta_value,o.id");
    $r['avpn_notes_11105']=$q("SELECT comment_post_ID oid,LEFT(comment_content,90) c,comment_date FROM {$p}comments WHERE comment_type='order_note' AND comment_content LIKE '%11105%' ORDER BY comment_date LIMIT 8");
    $r['av_be_stock_manage']=$q("SELECT COALESCE(ms.meta_value,'(nėra)') manage,COUNT(*) n,SUM(s.stock_qty) src_vnt FROM {$p}ps_sources s JOIN {$p}posts p ON p.ID=s.product_id AND p.post_status='publish' LEFT JOIN {$p}postmeta st ON st.post_id=s.product_id AND st.meta_key='_stock' LEFT JOIN {$p}postmeta ms ON ms.post_id=s.product_id AND ms.meta_key='_manage_stock' WHERE s.source='av' AND s.is_active=1 AND (st.meta_value IS NULL OR st.meta_value='') GROUP BY manage");
    $r['ean_vs_gtin_pvz']=$q("SELECT p.ID,LEFT(p.post_title,35) t,e.meta_value ean,g.meta_value gtin FROM {$p}postmeta e JOIN {$p}postmeta g ON g.post_id=e.post_id AND g.meta_key='_global_unique_id' JOIN {$p}posts p ON p.ID=e.post_id AND p.post_status='publish' WHERE e.meta_key='_ean' AND e.meta_value<>'' AND g.meta_value<>'' AND e.meta_value<>g.meta_value LIMIT 6");
    $r['ean_vs_gtin_tipai']=$q("SELECT SUM(g.meta_value REGEXP '^[0-9]{8,14}$') gtin_skaitinis,SUM(e.meta_value REGEXP '^[0-9]{8,14}$') ean_skaitinis,SUM(LENGTH(g.meta_value)<8) gtin_trumpas,COUNT(*) n FROM {$p}postmeta e JOIN {$p}postmeta g ON g.post_id=e.post_id AND g.meta_key='_global_unique_id' JOIN {$p}posts p ON p.ID=e.post_id AND p.post_status='publish' WHERE e.meta_key='_ean' AND e.meta_value<>'' AND g.meta_value<>'' AND e.meta_value<>g.meta_value");
    foreach(['plugins/petshop-feeds/petshop-feeds.php','plugins/petshop-xml/petshop-xml.php'] as $fp){ $c=@file_get_contents(WP_CONTENT_DIR.'/'.$fp); if($c===false){ $r['gtin_kodas'][$fp]='nėra'; continue; } preg_match_all('/[^\n]{0,60}(_global_unique_id|_ean\b|get_global_unique_id|g:gtin)[^\n]{0,60}/',$c,$m); $r['gtin_kodas'][$fp]=array_slice(array_unique(array_map('trim',$m[0])),0,8); }
    try{ $ctx=stream_context_create(['ssl'=>['capture_peer_cert_chain'=>true,'verify_peer'=>false,'verify_peer_name'=>false,'SNI_enabled'=>true,'peer_name'=>'petshop.lt']]); $so=@stream_socket_client('ssl://petshop.lt:443',$en,$es,10,STREAM_CLIENT_CONNECT,$ctx); if($so){ $pr=stream_context_get_params($so); $ch=$pr['options']['ssl']['peer_certificate_chain']??[]; $r['tls_chain']=array_map(function($c){ $x=openssl_x509_parse($c); return ($x['subject']['CN']??'?').' <- '.($x['issuer']['CN']??'?'); },$ch); fclose($so);} }catch(Throwable $e){ $r['tls_chain']='klaida '.$e->getMessage(); }
    $rs=wp_remote_get('https://petshop.lt/?ps_tls_test=1',['timeout'=>12,'sslverify'=>true,'redirection'=>0]); $r['tls_verify_from_server']=is_wp_error($rs)?$rs->get_error_message():wp_remote_retrieve_response_code($rs);
    $rs=wp_remote_get('https://petshop.lt/',['timeout'=>12,'sslverify'=>true,'redirection'=>0,'user-agent'=>'ps-audit']); $r['tls_verify_home']=is_wp_error($rs)?$rs->get_error_message():wp_remote_retrieve_response_code($rs);
    $r['cainfo']=[ini_get('curl.cainfo'),ini_get('openssl.cafile'),ABSPATH.WPINC.'/certificates/ca-bundle.crt',file_exists(ABSPATH.WPINC.'/certificates/ca-bundle.crt')];
    $c=$wpdb->get_var("SELECT code FROM {$p}snippets WHERE id=614"); preg_match_all('/[^\n]{0,90}(session|petshop_gtm_atc_queue)[^\n]{0,90}/i',(string)$c,$m); $r['snip614_session']=array_slice(array_map('trim',$m[0]),0,14);
    $r['sessions_su_krepseliu']=$q("SELECT COUNT(*) n,SUM(session_value LIKE '%\"cart\";s:%' AND session_value NOT LIKE '%\"cart\";s:6:\"a:0:{}\"%') su_prekem,SUM(session_value LIKE '%petshop_gtm_atc_queue%') gtm,SUM(session_value LIKE '%petshop_gtm_atc_queue\";s:6:\"a:0:{}\"%' OR session_value LIKE '%petshop_gtm_atc_queue\";a:0:{}%') gtm_tuscia FROM {$p}woocommerce_sessions");
    $r['sargas_strstr']=$q("SELECT url,kiek,laikas,LEFT(zinute,60) z FROM {$p}ps_sargas_klaidos WHERE zinute LIKE '%strstr%' ORDER BY kiek DESC LIMIT 8");
    $r['sargas_lygiai_7d']=$q("SELECT lygis,COUNT(*) n,SUM(kiek) kiek FROM {$p}ps_sargas_klaidos WHERE laikas>=NOW()-INTERVAL 7 DAY GROUP BY lygis");
    $r['sargas_fatal_urls']=$q("SELECT url,LEFT(zinute,70) z,kiek,laikas FROM {$p}ps_sargas_klaidos WHERE lygis LIKE '%fatal%' AND laikas>=NOW()-INTERVAL 7 DAY ORDER BY laikas DESC LIMIT 8");
    $r['login_sargas']=$q("SELECT option_name,LEFT(option_value,150) v FROM {$p}options WHERE option_name LIKE 'ps_login%' OR option_name LIKE '%login_sargas%' OR option_name LIKE '%uzrakt%' LIMIT 8");
    $r['login_tr']=$q("SELECT COUNT(*) n FROM {$p}options WHERE option_name LIKE '_transient_ps_login%' OR option_name LIKE '_transient_ps_sargas_login%'");
    foreach(['https://petshop.lt/wp-content/uploads/ps-backups/petshop-vertimai-v11-BACKUP-2026-09-08.php','https://petshop.lt/wp-content/uploads/ps-lipdukai/lipdukas-V07267E1000043.pdf','https://petshop.lt/wp-content/uploads/wpallimport/files/vf-feed.xml','https://petshop.lt/wp-content/uploads/wpallimport/files/goods_clean.xml','https://petshop.lt/wp-content/uploads/petshop-legacy/','https://petshop.lt/wp-content/uploads/wpallimport/logs/','https://petshop.lt/wp-content/petshop-private-logs/attr-engine.log'] as $u){ $rs=wp_remote_get($u,['timeout'=>12,'redirection'=>0,'sslverify'=>false,'user-agent'=>'Mozilla/5.0 ps-audit','limit_response_size'=>2000]); $r['http'][$u]=is_wp_error($rs)?'ERR':wp_remote_retrieve_response_code($rs).' '.substr((string)wp_remote_retrieve_header($rs,'content-type'),0,20).' '.wp_remote_retrieve_header($rs,'content-length').'B '.substr(preg_replace('/\s+/',' ',strip_tags((string)wp_remote_retrieve_body($rs))),0,50); }
    $opt=$wpdb->get_var("SELECT options FROM {$p}pmxi_imports WHERE id=3"); $o=@unserialize($opt); $keys=['update_all_data','is_update_status','is_update_content','is_update_title','is_update_excerpt','is_update_images','is_update_custom_fields','is_update_categories','is_update_attributes','is_update_dates','is_update_menu_order','is_update_parent','create_new_records','is_delete_missing','is_selective_hashing','records_per_request','is_scheduled','scheduling_enable','update_custom_fields_logic','update_images_logic','update_categories_logic','is_update_slug','is_update_author','is_update_comment_status','is_update_acf','is_fast_mode','do_not_remove_images','is_update_product_type']; if(is_array($o)) foreach($keys as $k) if(array_key_exists($k,$o)) $r['wpai3'][$k]=is_scalar($o[$k])?$o[$k]:json_encode($o[$k]); $r['wpai3_custom_fields']=is_array($o)&&isset($o['custom_name'])?array_slice((array)$o['custom_name'],0,20):null; $r['wpai3_product_fields']=is_array($o)?array_intersect_key($o,array_flip(['single_product_stock_qty','single_product_regular_price','single_product_sale_price','single_product_stock_status','product_manage_stock','single_product_ID','duplicate_matching','duplicate_indicator','custom_duplicate_name','custom_duplicate_value','single_product_sku'])):null;
    $opt7=$wpdb->get_var("SELECT options FROM {$p}pmxi_imports WHERE id=7"); $o7=@unserialize($opt7); if(is_array($o7)) foreach(['update_all_data','is_selective_hashing','records_per_request','is_update_images','is_update_custom_fields','create_new_records','is_delete_missing'] as $k) if(array_key_exists($k,$o7)) $r['wpai7'][$k]=is_scalar($o7[$k])?$o7[$k]:json_encode($o7[$k]);
    $hits=[]; foreach(glob(WP_CONTENT_DIR.'/mu-plugins/*.php') as $fx){ $c=file_get_contents($fx); if(preg_match('/DELETE\s+FROM\s+[^\n]{0,40}(ps_carts|ps_web_ivykiai|ps_ivykiai|woocommerce_sessions|ps_sargas_klaidos|ps_email_jobs)/i',$c,$m)) $hits[basename($fx)][]=$m[1]; } $r['valymo_kodas']=$hits;
    $r['carts_dienos']=$q("SELECT DATE(created_at) d,COUNT(*) n FROM {$p}ps_carts WHERE created_at>=NOW()-INTERVAL 4 DAY GROUP BY d");
    $r['ivykiai_seniausi']=$q("SELECT (SELECT MIN(laikas) FROM {$p}ps_web_ivykiai) web,(SELECT COUNT(*) FROM {$p}ps_web_ivykiai WHERE laikas<NOW()-INTERVAL 14 DAY) web_seni");
    $r['sesiju_valanda']=$q("SELECT COUNT(*) n FROM {$p}woocommerce_sessions WHERE session_expiry BETWEEN UNIX_TIMESTAMP()+172800-3600 AND UNIX_TIMESTAMP()+172800");
    $r['reduced0']=$q("SELECT COUNT(DISTINCT i.order_id) uzs,COUNT(*) eil FROM {$p}woocommerce_order_itemmeta im JOIN {$p}woocommerce_order_items i ON i.order_item_id=im.order_item_id WHERE im.meta_key='_reduced_stock' AND im.meta_value='0'");
    $r['reduced0_pvz']=$q("SELECT i.order_id,o.status,o.date_created_gmt FROM {$p}woocommerce_order_itemmeta im JOIN {$p}woocommerce_order_items i ON i.order_item_id=im.order_item_id JOIN {$p}wc_orders o ON o.id=i.order_id WHERE im.meta_key='_reduced_stock' AND im.meta_value='0' GROUP BY i.order_id,o.status,o.date_created_gmt ORDER BY i.order_id DESC LIMIT 8");
    $r['ivykiai_36250']=$q("SELECT * FROM {$p}ps_uzsakymu_ivykiai WHERE order_id IN (36250,36145) ORDER BY id LIMIT 12");
  }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.basename($e->getFile()).':'.$e->getLine(); }
  $r['trukme_s']=round(microtime(true)-$T0,1);
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($r,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit;
},1);
