<?php
/** Plugin Name: TEMP PS S1719j — saugumo paketas: 1 sausas, 2 vykdyti (.htaccess deny, šiukšlės → archyvas, snippet 465 off, testuotojas), 3 patikra, 9 atstatymas */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1719j'])) return; $f=$_GET['ps_s1719j']; $r=['v'=>'S1719j','faze'=>$f,'t'=>date('Y-m-d H:i:s')]; @set_time_limit(200);
  global $wpdb; $p=$wpdb->prefix; $up=wp_upload_dir()['basedir']; $arch='/home/gyvunai2/domains/petshop.lt/ps-archyvas'; $trash=$arch.'/s1719-trash';
  $DENY="# S1719 (2026-09-25) saugumas: katalogas neatiduodamas per HTTP (failus skaito tik PHP/darbalaukis)\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n<IfModule !mod_authz_core.c>\nOrder deny,allow\nDeny from all\n</IfModule>\n";
  $DIRS=[$up.'/ps-lipdukai',$up.'/wpallimport',$up.'/petshop-legacy',$up.'/ps-backups',WP_CONTENT_DIR.'/petshop-private-logs'];
  $ROOT="\n# BEGIN Petshop Saugumas uploads (S1719, 2026-09-25)\n# PHP uploads'e nevykdomas; tiekeju feed'ai (savikaina) neatiduodami\n<FilesMatch \"\\.(php|phtml|php[0-9]|phar)$\">\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n</FilesMatch>\n<FilesMatch \"^(petshop-vf-cache\\.xml|vetfarmas_response.*\\.xml)$\">\n<IfModule mod_authz_core.c>\nRequire all denied\n</IfModule>\n</FilesMatch>\n# END Petshop Saugumas uploads\n";
  $TRASH=array_merge(glob($up.'/*_result.json')?:[],glob($up.'/lookupdiag.json')?:[],glob($up.'/vetfarmas_response_*.xml')?:[],array_filter([ABSPATH.'wp-content/phptest.php',ABSPATH.'index.html.backup.5a6defd0b6c8b4cd418a970086e2c0b4'],'file_exists'));
  $URLS=['/wp-content/uploads/ps-lipdukai/lp/LP-1160-HC039608415LT.pdf','/wp-content/uploads/ps-lipdukai/lipdukas-V07267E1000043.pdf','/wp-content/uploads/wpallimport/files/vf-feed.xml','/wp-content/uploads/wpallimport/files/goods_clean.xml','/wp-content/uploads/petshop-vf-cache.xml','/wp-content/uploads/vetfarmas_response_20260602_142756.xml','/wp-content/uploads/ps-backups/petshop-legacy-301-map.json.bak_s1669','/wp-content/uploads/ps-backups/google.xml.bak_s1671','/wp-content/uploads/cmp_result.json','/wp-content/petshop-private-logs/attr-engine.log','/wp-content/phptest.php','/index.html.backup.5a6defd0b6c8b4cd418a970086e2c0b4','/wp-content/uploads/wpallimport/index.php','/wp-content/uploads/2026/09/','/','/feed/google/','/wp-content/uploads/pmax-s1672/manifest.json'];
  $http=function() use($URLS){ $o=[]; foreach($URLS as $u){ $rs=wp_remote_get('https://petshop.lt'.$u,['timeout'=>12,'redirection'=>0,'sslverify'=>false,'user-agent'=>'Mozilla/5.0 ps-audit','limit_response_size'=>800]); $o[$u]=is_wp_error($rs)?'ERR':wp_remote_retrieve_response_code($rs); } return $o; };
  try{
  if($f==='1'){ foreach($DIRS as $d) $r['dirs'][str_replace(ABSPATH,'',$d)]=[is_dir($d),file_exists($d.'/.htaccess')]; $r['uploads_ht_turi_s1719']=strpos(file_get_contents($up.'/.htaccess'),'S1719')!==false; $r['trash']=array_map(function($x){return str_replace(ABSPATH,'',$x);},$TRASH); $r['snippet465']=$wpdb->get_row("SELECT id,name,active FROM {$p}snippets WHERE id=465",ARRAY_A); $u=get_user_by('login','testuotojas'); $r['testuotojas']=$u?$u->ID:null; $r['deactivate_fn']=function_exists('deactivate_snippet'); $r['http_pries']=$http(); }
  if($f==='2'){ if(!is_dir($trash)) wp_mkdir_p($trash);
    foreach($DIRS as $d){ if(!is_dir($d)){ $r['ht'][$d]='nėra katalogo'; continue; } $h=$d.'/.htaccess'; if(file_exists($h)&&strpos(file_get_contents($h),'S1719')===false) copy($h,$trash.'/'.basename($d).'.htaccess.bak_s1719'); file_put_contents($h,$DENY); $r['ht'][str_replace(ABSPATH,'',$d)]=file_exists($h); }
    $uh=$up.'/.htaccess'; $cur=file_get_contents($uh); if(strpos($cur,'S1719')===false){ copy($uh,$arch.'/uploads.htaccess.bak_s1719'); file_put_contents($uh,$cur.$ROOT); } $r['uploads_ht']=strlen(file_get_contents($uh));
    foreach($TRASH as $t){ $dst=$trash.'/'.basename($t); $r['perkelta'][basename($t)]=rename($t,$dst)?'→ s1719-trash':'NEPAVYKO'; }
    if(function_exists('deactivate_snippet')){ deactivate_snippet(465); } else { $wpdb->update("{$p}snippets",['active'=>0],['id'=>465]); } wp_cache_flush(); $r['snippet465']=$wpdb->get_row("SELECT id,active FROM {$p}snippets WHERE id=465",ARRAY_A);
    require_once ABSPATH.'wp-admin/includes/user.php'; $u=get_user_by('login','testuotojas'); if($u&&$u->ID==75){ $r['testuotojas_istrintas']=wp_delete_user(75); } else $r['testuotojas']='nerastas/kitas ID';
    $hb=wp_remote_get('https://petshop.lt/?ps_hb='.time(),['timeout'=>20,'sslverify'=>false]); $r['hb']=is_wp_error($hb)?'ERR':wp_remote_retrieve_response_code($hb);
    $r['http_po']=$http(); }
  if($f==='3'){ $r['http']=$http(); $r['lp_pdf_diske']=file_exists($up.'/ps-lipdukai/lp/LP-1160-HC039608415LT.pdf'); $r['vf_cache_diske']=file_exists($up.'/petshop-vf-cache.xml'); $r['snippet465']=$wpdb->get_row("SELECT id,active FROM {$p}snippets WHERE id=465",ARRAY_A); $r['testuotojas']=get_user_by('login','testuotojas')?'yra':'nėra'; $r['trash_dir']=array_map('basename',glob($trash.'/*')?:[]); }
  if($f==='9'){ foreach($DIRS as $d){ $h=$d.'/.htaccess'; if(file_exists($h)&&strpos(file_get_contents($h),'S1719')!==false) unlink($h); $b=$trash.'/'.basename($d).'.htaccess.bak_s1719'; if(file_exists($b)) copy($b,$h); } $b=$arch.'/uploads.htaccess.bak_s1719'; if(file_exists($b)) copy($b,$up.'/.htaccess'); foreach(glob($trash.'/*')?:[] as $t){ $n=basename($t); if(strpos($n,'.htaccess.bak')!==false) continue; $dst=($n==='phptest.php')?ABSPATH.'wp-content/'.$n:((strpos($n,'index.html.backup')===0)?ABSPATH.$n:$up.'/'.$n); rename($t,$dst); $r['grazinta'][]=$n; } if(function_exists('activate_snippet')) activate_snippet(465); else $wpdb->update("{$p}snippets",['active'=>1],['id'=>465]); $r['pastaba']='testuotojas negrąžinamas (ištrintas)'; $r['http']=$http(); }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.$e->getLine(); }
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($r,JSON_UNESCAPED_UNICODE); exit;
},1);
