<?php
/** Plugin Name: TEMP PS S1724y rytas v1.8: lempute "rinkiniai be nuotraukos". Fazes: 1 dry, 2 patch, 3 patikra, 9 atstatyti (.bak_s1724c) */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1724y'])) return; $f=(string)$_GET['ps_s1724y']; $r=['v'=>'S1724y','faze'=>$f]; $ry=WPMU_PLUGIN_DIR.'/petshop-rytas.php'; $arch=dirname(untrailingslashit(ABSPATH)).'/ps-archyvas';
  $tok=function($code){ try{ token_get_all($code,TOKEN_PARSE); return 'ok'; }catch(Throwable $e){ return 'KLAIDA '.$e->getMessage(); } };
  $blk="\t\t/* rinkiniai be nuotraukos (S1724): publikuoti MnM rinkiniai, kurių thumbnail nėra arba failo diske nėra */\n\t\ttry {\n\t\t\t\$rk_ = \$wpdb->get_results( \"SELECT p.ID, p.post_title, (SELECT meta_value FROM {\$wpdb->postmeta} WHERE post_id = p.ID AND meta_key = '_thumbnail_id' LIMIT 1) thumb FROM {\$wpdb->posts} p JOIN {\$wpdb->term_relationships} tr ON tr.object_id = p.ID JOIN {\$wpdb->term_taxonomy} tt ON tt.term_taxonomy_id = tr.term_taxonomy_id AND tt.taxonomy = 'product_type' JOIN {\$wpdb->terms} t ON t.term_id = tt.term_id AND t.slug = 'mix-and-match' WHERE p.post_type = 'product' AND p.post_status = 'publish'\", ARRAY_A );\n\t\t\t\$be_ = array();\n\t\t\tforeach ( (array) \$rk_ as \$x_ ) { \$tid_ = (int) \$x_['thumb']; \$ok_ = \$tid_ && ( \$fp_ = get_attached_file( \$tid_ ) ) && is_file( \$fp_ ); if ( ! \$ok_ ) { \$pr_ = function_exists( 'wc_get_product' ) ? wc_get_product( (int) \$x_['ID'] ) : null; \$iid_ = \$pr_ ? (int) \$pr_->get_image_id() : 0; if ( ! \$iid_ || ! ( \$fp_ = get_attached_file( \$iid_ ) ) || ! is_file( \$fp_ ) ) \$be_[] = '#' . \$x_['ID'] . ' ' . mb_substr( \$x_['post_title'], 0, 30 ); } }\n\t\t\t\$add( 'rinkiniai_foto', \$be_ ? ( count( \$be_ ) >= 3 ? 'raudona' : 'geltona' ) : 'zalia', 'Rinkiniai be nuotraukos: ' . count( \$be_ ) . ' iš ' . count( (array) \$rk_ ) . ( \$be_ ? ' — ' . implode( ', ', array_slice( \$be_, 0, 4 ) ) : '' ) );\n\t\t} catch ( \\Throwable \$e_ ) { \$add( 'rinkiniai_foto', 'pilka', 'Rinkiniai be nuotraukos: ' . \$e_->getMessage() ); }\n";
  $rp=function($s) use($blk){ $s=str_replace(" * Version: 1.7\n"," * Version: 1.8\n",$s,$c1); $a="\t\t/* neišsiųsti */\n"; $s=str_replace($a,$blk.$a,$s,$c2); return [$s,[$c1,$c2]]; };
  try{
    if($f==='1'){ list($p,$c)=$rp(file_get_contents($ry)); $r['counts']=$c; $r['lint']=$tok($p); $r['jau']=strpos(file_get_contents($ry),'rinkiniai_foto')!==false; $r['md5_dabar']=md5_file($ry); }
    if($f==='2'){ $s=file_get_contents($ry); list($p,$c)=$rp($s); if($c[0]!==1||$c[1]!==1||$tok($p)!=='ok') throw new Exception('patch '.json_encode($c).' '.$tok($p)); if(!is_file($arch.'/petshop-rytas.php.bak_s1724c')) copy($ry,$arch.'/petshop-rytas.php.bak_s1724c'); file_put_contents($ry,$p); $r['md5']=md5_file($ry); $x=wp_remote_get(home_url('/?ps_hb='.time()),['timeout'=>25,'sslverify'=>false]); $r['heartbeat']=wp_remote_retrieve_response_code($x); if($r['heartbeat']!==200){ copy($arch.'/petshop-rytas.php.bak_s1724c',$ry); $r['ROLLBACK']=true; } }
    if($f==='3'){ $m=new ReflectionMethod('Petshop_Rytas','patikros'); $m->setAccessible(true); $pt=$m->invoke(null); foreach($pt as $x){ if(in_array($x['kodas'],['rinkiniai_foto','botu_uztvara'])) $r['l'][]=$x; } $r['n']=count($pt); $r['md5']=md5_file($ry); }
    if($f==='9'){ copy($arch.'/petshop-rytas.php.bak_s1724c',$ry); $r['md5']=md5_file($ry); }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.$e->getLine(); }
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($r,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE); exit;
}, 1);
