<?php
/** Plugin Name: TEMP PS S1736o snippet 570 v1.1 DP puslapis su puslapiavimu (1 dry / 2 deploy / 3 patikra / 9 atstato) */
add_action('wp_loaded', function(){
  if(!isset($_GET['ps_s1736o'])) return;
  $f=$_GET['ps_s1736o']; @set_time_limit(250); global $wpdb; $T=$wpdb->prefix.'snippets'; $r=['v'=>'S1736o','faze'=>$f];
  $OLD='8b17aa9172226586fbd744b5ef885e19'; $NEW='436f0a193ca7008e145f773a12aef314'; $BAK='ps_s1736_snip570_bak';
  $get=function($u){ $x=wp_remote_get($u,['timeout'=>40,'sslverify'=>false,'headers'=>['Cookie'=>'ps_js=1']]); if(is_wp_error($x)) return ['ERR',$x->get_error_message()]; return [wp_remote_retrieve_response_code($x),wp_remote_retrieve_body($x)]; };
  $matuoti=function($q='') use($get){ $u=home_url('/daugiau-pigiau/?ps_hb='.time().rand(10,99).$q); list($c,$h)=$get($u); preg_match_all('~data-product_id="(\d+)"~',$h,$m); preg_match_all('~product-page=(\d+)~',$h,$p); $vis=''; if(preg_match('~Visos <span class="psc-dp-count">\((\d+)\)~',$h,$v)) $vis=$v[1]; return ['http'=>$c,'prekiu'=>count(array_unique($m[1])),'puslapiai'=>array_values(array_unique($p[1])),'visos'=>$vis]; };
  $kesas=function(){ $dir=WP_CONTENT_DIR.'/cache/supercache/'.wp_parse_url(home_url(),PHP_URL_HOST).'/daugiau-pigiau'; if(is_dir($dir)){ if(function_exists('prune_super_cache')) prune_super_cache($dir,true); else { foreach(glob($dir.'/*') as $x) @unlink($x); @rmdir($dir); } } return is_dir($dir)?'liko':'isvalyta'; };
  try{
    $s=$wpdb->get_row("SELECT id,code,active FROM $T WHERE id=570",ARRAY_A); $live=md5($s['code']); $nc=gzuncompress(base64_decode('eNqdGE1z28b17l/xTLMB6CEhkvqwA5p0MxHjqklkV1Kcg4bDWQBLckUAi+4uaNEazfQP9NYZ3zrJ2cec25P1R/pL+nYXAAmZiqcdaUjg7fv+Xu49ffoInsIbquSCZ3BM8jkj+fAN01+Q5TImGeOAh0KFPKKw6nk9TaG/wT3vPds/akO/2z/qdL/u9L9u+SB49OkDKLaEg+eQMZHkEjKyxE+XCEHWUxmzkLYhoCX/u99abUi5kPCfv/3zLZMcUfv7h60Gvv9DCwOISEAErJhkbci44Wxo11cUZKUoWbEkB/fnb+EyQzXyUGnRc5YSRSdteFkAOwijw9OWp3lfZjKcRtbuaWbsnkBHW8G1PFS7UXrFnjaQZbh0tD0qFwymUTYNiKTTgvuURZbzMcpNWMokzNeru48phxmLlSDSh2Q9V/mSSCMmwe+Lk+/hijJQHA0Sdx/vftWWrQVBN6UKekam4XpB8FkxiPmcLQkwAVKxmKE6S8Iy+GYZsqu737bc48qUZRlVcHh0ZBTbe/SIRNG0iqnrfO4Cpw2zPA0V46nbJErJ1s0jAPMEw006TDXAhtXFcwAno2Kq3evAcIRhaltoyOM8SaUDBqqBGHHDrQ27pLcGiIL/85gHJIbmuywKCtDeHvQ8wCxhcPzGhoKw3wmFUTuO8VFrbjh1RnOqpqiT2zDqnY9/GH97Accn5xcnp/iQeSfH8N3Z6x/hpsDPuFTyFjKDfnJ6Oj6DP78+Oa2dJ1QRREng9Sl+ehqEQoeG2TenxxqmUaZLuh46OzR1DPOf/zQ+G6MGhlytMzp0ChTHcrEnUhGVSzzLg5jJhdMwHtsy1JZaQjLXYalakdhpV8eld9kMXJpkau1WJy24MWoIig5NwXmRje5+YTkHVD3X5VnUAkrYVINkdx/jdYJZl376IIj3Yi8bOVrGbRWyvgevTBEg0hKrcc4Fu8I6x/TV2VpEEiTm8Ke/62R2I1M9GoDV+Pbk/PU5iFyupQkopjO2kXxeWVpkn8xTlug0A5Npzt0vFlCkoZa8ffw9UZ8+bI7nguTvsag0ij5+he93/7aAAiUj+VKGrEJ5g+93v6LKWzjv81VdiX9ZgEn7wvVN3QqwVEKep2pjhY0iS3UsMMYCD1iSxaZI2zsiOOOCknAB7pZHsJs09ZOW3YxJQOMyqE2F/HTqo+RkGqxdR+NptvpbV2KRjCFRtgRtjjxuqhaEPFUszakFG0UQrZ5tVMxp0Q2aqjMyYrAE2xuh4YLFkaDp9vl9wYXkZhaTkC54HFEh7zviwfQudKqYaEcuqKAP1f7/XP07699YImhMdMOUC5YhOkYPO4ESHg+uaFj1gi8wUeSapzxZI70y9MqrwTUb5HkfZnqDxi1Aw5pLC5llb0H7UKy7lWetit6GxJ5vB6DVKDyKxfzjQ9Nre14JuqQDWDKlp5KMKU5nRK1yyiS+W4WnBSPolnl6vzwuTX5O6rVuSs2kt7PJ9PbmyJCao/uitpAQ5tgq3ZlQn5EUPrit9bZ9D6euWq+waxUD3rRiHJ4rnXZMSorip6/GF5cObgJ5SqQzacFLkCRlir2neiTsQPDBMV1Uu6tk99VX8LhgeM9FFmGCHXwj2tJbLQ88+E5rl3NcHk6O5eeMv8S3aCL2nEblRN2Nf2l8OzFTAGgs6UPkRUerj4tDD85xxYBgjdtelseMiNxmTy4R7ta41FaVdjNoFZIkQf4uRrNl+o+Zm3oCayxHcUXiqSQxxcaMXqFlw5DBQ1TBw1TFuNTEHS3YWNPaOP/Igx9YwpSdXXZDqsSYPehyszlNBppEL9g+pDSgSyIyLDO9DJeLbs6vyK4dtxL4zIMzmmLhMu00HuiFAf1m54tZPHIR601OCcWXmHzn47O347NL52z8l5/G5xfTn85OHFyZnZd2EDSt5SbISFaU1L1pRMMFx5UhYisIYyLlsIGrXSfKOjZaDbsUFFgyI+lOtI6p5MbojEdrxfwXexqzRkpgIehs2HA8iqsjGuJWJrU8p3GPa6BSxyvzfDgcOmgT5nrHAhzfcTTRyN47dqlljG2MXMfb9oLntArVXuwRq95mGtene20iR0SRqpZsEEor9Fb+15yK9ZSIuVu1grYdzxsbq9kmp1WpV4WMFlppusNsG1r1kx1+1Io84LmNFO0l6/KFStDn2pLLogVP0Idfcp7Ft315ssN9t5sI72EOjZx6Wkm1junI6O/VEuYmQXex1O9CF/oH2fUgQ0eydO73jrJr6A4CLrAQOgFXiid+D2GSxzjjntBD/TeImMRJt/ZnMb0e6I/OO0EyX38M5vjwHFmSmM3TDtProx/ihKPidocmNnVvZrgqdd5RNl8o/6jbHVj9OsIANDdcP7jwn+zv79e5oMNvSm1YGrOUdoKYh8vKIiQGbdUgwG15LtCVkf9kdqj/SjMFiXB/9vvdmpyBoteqE9GQC7Oj+ClP6cAoKnEC+T3tNxxdqWTmGCsbvN6hBIpJNzCaLKxBPe/gM6X9BV9hHLaVKnxbaNBFL+zS4DNOXpWvNW59tPDgqOQ2m81+h3CHMv2jg3D/+YPkJiVvON5AmFr73rNtv/TRL0X8YjpTPr5b4j8mNGIE3IRgvrBILXSos+tWucLszAyL2Ot2/1AyLbLyoGRbT4Yy7jqRjSpbmu2XJPoTa8mUh7N1tXtc3O22Z+VmjD90w6hhF42muL7fn1jlrX5SoMV6xOmZXo04XOqwC23e/XJy7JBiyjzi279LbCYcopk+VWhtepWVbsDFswYbJQzQPGlQOR6HDT2yG2AKJVhjj9LDfcrSxsROudqmUrQdcwHWv8psrq348n/ehIs9AeexuYXElKR6JuOq8F/nZ0X1'));
    $tok=true; try{ token_get_all("<?php\n".$nc,TOKEN_PARSE); }catch(Throwable $e){ $tok=$e->getMessage(); }
    $r['live']=$live; $r['live_ok']=$live===$OLD; $r['new_ok']=md5($nc)===$NEW; $r['tok']=$tok; $r['active']=$s['active'];
    if($f==='1'){ $r['pries']=$matuoti(); }
    if($f==='2'){
      if(!($live===$OLD && md5($nc)===$NEW && $tok===true)){ $r['STOP']=1; }
      else{ if(!get_option($BAK)) update_option($BAK,base64_encode(gzcompress($s['code'],9)),false);
        $wpdb->update($T,['code'=>$nc,'modified'=>current_time('mysql',1)],['id'=>570]);
        if(function_exists('\Code_Snippets\clean_snippets_cache')) \Code_Snippets\clean_snippets_cache($T); wp_cache_flush_group('code_snippets');
        $r['irasyta']=md5($wpdb->get_var("SELECT code FROM $T WHERE id=570"));
        $x=wp_remote_get(home_url('/?ps_hb='.time()),['timeout'=>25,'sslverify'=>false,'redirection'=>0]); $r['hb']=is_wp_error($x)?'ERR':wp_remote_retrieve_response_code($x);
        if(!is_int($r['hb'])||$r['hb']>=500){ $wpdb->update($T,['code'=>$s['code']],['id'=>570]); $r['ATSTATYTA']=1; }
        $r['kesas']=$kesas(); } }
    if($f==='3'){ $r['p1']=$matuoti(); $r['p2']=$matuoti('&product-page=2'); $r['p5']=$matuoti('&product-page=5'); $r['katems']=$matuoti('&gyvunas=katems'); $r['katems_p2']=$matuoti('&gyvunas=katems&product-page=2'); }
    if($f==='9'){ $b=get_option($BAK); if($b){ $wpdb->update($T,['code'=>gzuncompress(base64_decode($b))],['id'=>570]); $r['atstatyta']=md5($wpdb->get_var("SELECT code FROM $T WHERE id=570")); $r['kesas']=$kesas(); } }
  }catch(Throwable $e){ $r['FATAL']=$e->getMessage().' @'.$e->getLine(); }
  header('Content-Type: application/json; charset=utf-8'); echo json_encode($r,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE|JSON_PARTIAL_OUTPUT_ON_ERROR); exit;
}, 1);
